FROM ubuntu:16.10
MAINTAINER Carlos O'Ryan <coryan@users.noreply.github.com>

RUN apt-get update && apt-get install -y \
    libboost-atomic1.61.0 \
    libboost-chrono1.61.0 \
    libboost-context1.61.0 \
    libboost-coroutine1.61.0 \
    libboost-date-time1.61.0 \
    libboost-filesystem1.61.0 \
    libboost-graph-parallel1.61.0 \
    libboost-graph1.61.0 \
    libboost-iostreams1.61.0 \
    libboost-locale1.61.0 \
    libboost-log1.61.0 \
    libboost-math1.61.0 \
    libboost-mpi-python1.61.0 \
    libboost-mpi1.61.0 \
    libboost-program-options1.61.0 \
    libboost-python1.61.0 \
    libboost-random1.61.0 \
    libboost-regex1.61.0 \
    libboost-serialization1.61.0 \
    libboost-signals1.61.0 \
    libboost-system1.61.0 \
    libboost-test1.61.0 \
    libboost-thread1.61.0 \
    libboost-timer1.61.0 \
    libboost-type-erasure1.61.0 \
    libboost-wave1.61.0 \
    libbz2-1.0 \
    libclfft2 \
    libfftw3-3 \
    libyaml-cpp0.5v5 \
    lshw \
    ocl-icd-libopencl1 \
    sudo \
    time \
    zlib1g

RUN apt-get clean
