JayBeams: jb/fftw/bm_time_delay_estimator.cpp File Reference
bm_time_delay_estimator.cpp File Reference
#include <jb/fftw/time_delay_estimator.hpp>
#include <jb/testing/create_square_timeseries.hpp>
#include <jb/testing/delay_timeseries.hpp>
#include <jb/testing/microbenchmark.hpp>
#include <jb/testing/microbenchmark_group_main.hpp>
#include <chrono>
#include <iostream>
#include <stdexcept>
#include <string>
Namespaces
defaults
Define defaults for program parameters.
Macros
#define JB_FFTW_DEFAULT_fftw_bm_time_delay_estimator_test_case "float:aligned"
Functions
int main (int argc, char *argv[])
Macro Definition Documentation
JB_FFTW_DEFAULT_fftw_bm_time_delay_estimator_test_case
#define JB_FFTW_DEFAULT_fftw_bm_time_delay_estimator_test_case "float:aligned"
Definition at line 145 of file bm_time_delay_estimator.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 34 of file bm_time_delay_estimator.cpp.
References jb::testing::create_square_timeseries(), jb::testing::delay_timeseries_periodic(), jb::detail::nsamples(), jb::testing::microbenchmark< Fixture >::run(), and jb::testing::defaults::size.