JayBeams: jb::itch5::order_book Class Reference
jb::itch5::order_book Class Reference
Maintain the ITCH-5.0 order book for a single security.
#include <order_book.hpp>
Public Member Functions
order_book ()
Initialize an empty order book.
bool handle_add_order (buy_sell_indicator_t side, price4_t px, int qty)
Handle a new order.
bool handle_order_reduced (buy_sell_indicator_t side, price4_t px, int reduced_qty)
Handle an order reduction, which includes executions, cancels and replaces.
Accessors
half_quote best_bid () const
half_quote worst_bid () const
half_quote best_offer () const
half_quote worst_offer () const
std::size_t buy_count () const
std::size_t sell_count () const
book_depth_t get_book_depth () const
Static Public Member Functions
static half_quote empty_bid ()
The value used to represent an empty bid.
static half_quote empty_offer ()
The value used to represent an empty offer.
Private Types
typedef std::map< price4_t, int, std::greater< price4_t > > buys
typedef std::map< price4_t, int, std::less< price4_t > > sells
Private Member Functions
template<typename book_side >
bool handle_add_order (book_side &side, price4_t px, int qty)
Refactor handle_add_order()
template<typename book_side >
bool handle_order_reduced (book_side &side, price4_t px, int reduced_qty)
Refactor handle_order_reduce()
Private Attributes
buys buy_
sells sell_
Detailed Description
Maintain the ITCH-5.0 order book for a single security.
ITCH-5.0, like other market data feeds provide order-by-order detail, that is, the feed includes a message for each order received by the exchange, as well as the changes to these orders, i.e. when the execute, when their quantity (and/or price) is modified, and when they are canceled.. Such feeds are sometimes called Level III feeds. Typically only orders that do not immediately execute in full are included in the feed.
There is substantial variation in the format of the messages, and some variation as to whether executions are represented differently than a partial cancel, and whether changes in price are allowed or create new order ids.
This class receives a stream of (unnormalized) ITCH-5.0 messages for a single security, and organizes the orders in a book, i.e. a data structure where orders at the same price are grouped together, and one can quickly ask:
What is the best bid (highest price of BUY orders) and what is the total quantity available at that price?
What is the best offer (lowest price of SELL orders) and what is the total quantity available at that price?
Definition at line 46 of file order_book.hpp.
Member Typedef Documentation
typedef std::map<price4_t, int, std::greater<price4_t> > jb::itch5::order_book::buys private
Definition at line 177 of file order_book.hpp.
typedef std::map<price4_t, int, std::less<price4_t> > jb::itch5::order_book::sells private
Definition at line 178 of file order_book.hpp.
Constructor & Destructor Documentation
jb::itch5::order_book::order_book () inline
Initialize an empty order book.
Definition at line 49 of file order_book.hpp.
Member Function Documentation
jb::itch5::half_quote jb::itch5::order_book::best_bid () const
Returns
the best bid price and quantity
Definition at line 3 of file order_book.cpp.
References buy_, and empty_bid().
Referenced by BOOST_AUTO_TEST_CASE(), empty_offer(), jb::itch5::generate_inside(), and jb::itch5::record_latency_stats().
jb::itch5::half_quote jb::itch5::order_book::best_offer () const
Returns
the best offer price and quantity
Definition at line 19 of file order_book.cpp.
References empty_offer(), and sell_.
Referenced by BOOST_AUTO_TEST_CASE(), empty_offer(), jb::itch5::generate_inside(), and jb::itch5::record_latency_stats().
std::size_t jb::itch5::order_book::buy_count () const inline
Returns
the number of levels with non-zero quantity for the BUY side.
Definition at line 76 of file order_book.hpp.
References buy_.
Referenced by get_book_depth().
static half_quote jb::itch5::order_book::empty_bid () inline static
The value used to represent an empty bid.
Definition at line 53 of file order_book.hpp.
Referenced by best_bid(), BOOST_AUTO_TEST_CASE(), and worst_bid().
static half_quote jb::itch5::order_book::empty_offer () inline static
The value used to represent an empty offer.
Definition at line 57 of file order_book.hpp.
References best_bid(), best_offer(), worst_bid(), and worst_offer().
Referenced by best_offer(), BOOST_AUTO_TEST_CASE(), and worst_offer().
book_depth_t jb::itch5::order_book::get_book_depth () const inline
Returns
the book depth, this is the number of price levels on this order book.
Definition at line 87 of file order_book.hpp.
References buy_count(), and sell_count().
Referenced by BOOST_AUTO_TEST_CASE().
bool jb::itch5::order_book::handle_add_order (buy_sell_indicator_t side, price4_t px, int qty) inline
Handle a new order.
Update the quantity at the right price level in the correct side of the book.
Parameters
side whether the order is a buy or a sell
px the price of the order
qty the quantity of the order
Returns
true if the inside changed
Definition at line 103 of file order_book.hpp.
References buy_, and sell_.
Referenced by BOOST_AUTO_TEST_CASE().
template<typename book_side > bool jb::itch5::order_book::handle_add_order (book_side & side, price4_t px, int qty) inline private
Refactor handle_add_order()
Template Parameters
book_side the type used to represent the buy or sell side of the book
Parameters
side the side of the book to update
px the price of the new order
qty the quantity of the new order
Returns
true if the inside changed
Definition at line 139 of file order_book.hpp.
bool jb::itch5::order_book::handle_order_reduced (buy_sell_indicator_t side, price4_t px, int reduced_qty) inline
Handle an order reduction, which includes executions, cancels and replaces.
Parameters
side whether the order is a buy or a sell
px the price of the order
reduced_qty the executed quantity of the order
Returns
true if the inside changed
Definition at line 119 of file order_book.hpp.
References buy_, and sell_.
Referenced by BOOST_AUTO_TEST_CASE(), and jb::itch5::compute_book::do_reduce().
template<typename book_side > bool jb::itch5::order_book::handle_order_reduced (book_side & side, price4_t px, int reduced_qty) inline private
Refactor handle_order_reduce()
Template Parameters
book_side the type used to represent the buy or sell side of the book
Parameters
side the side of the book to update
px the price of the order that was reduced
reduced_qty the quantity reduced in the order
Returns
true if the inside changed
Definition at line 156 of file order_book.hpp.
References JB_LOG, and jb::warning.
std::size_t jb::itch5::order_book::sell_count () const inline
Returns
the number of levels with non-zero quantity for the SELL side.
Definition at line 81 of file order_book.hpp.
References sell_.
Referenced by get_book_depth().
jb::itch5::half_quote jb::itch5::order_book::worst_bid () const
Returns
the worst bid price and quantity
Definition at line 11 of file order_book.cpp.
References buy_, and empty_bid().
Referenced by BOOST_AUTO_TEST_CASE(), and empty_offer().
jb::itch5::half_quote jb::itch5::order_book::worst_offer () const
Returns
the worst offer price and quantity
Definition at line 27 of file order_book.cpp.
References empty_offer(), and sell_.
Referenced by BOOST_AUTO_TEST_CASE(), and empty_offer().
Member Data Documentation
buys jb::itch5::order_book::buy_ private
Definition at line 180 of file order_book.hpp.
Referenced by best_bid(), buy_count(), handle_add_order(), handle_order_reduced(), and worst_bid().
sells jb::itch5::order_book::sell_ private
Definition at line 181 of file order_book.hpp.
Referenced by best_offer(), handle_add_order(), handle_order_reduced(), sell_count(), and worst_offer().
The documentation for this class was generated from the following files:
jb/itch5/order_book.hpp
jb/itch5/order_book.cpp