JayBeams: thread_config Class Reference
thread_config Class Reference
A configuration class for threads.
Public Member Functions
thread_config ()
config_object_constructors (thread_config)
int native_scheduling_policy () const
int native_priority () const
Public Member Functions inherited from jb::config_object
config_object ()
Default constructor.
config_object (config_object const &rhs)
Copy constructor.
config_object (config_object &&rhs)
Move constructor.
virtual ~config_object ()
Destructor.
config_object & operator= (config_object rhs)
Copy & swap assignment.
void swap (config_object &rhs)
Derived classes should implement member by member swap.
void load_overrides (int &argc, char *argv[], std::string const &filename, char const *environment_variable_name)
Read the configuration file and load the overrides defined therein.
void load_overrides (int &argc, char *argv[], std::string const &filename)
Read the configuration file and load the overrides defined therein.
void load_overrides (int &argc, char *argv[], std::istream &is)
Read the configuration file and load the overrides defined therein.
void process_cmdline (int &argc, char *argv[])
Process the command line.
virtual void validate () const
Validate the settings.
std::ostream & to_stream (std::ostream &os) const
Print out the settings.
Public Attributes
jb::config_attribute< thread_config, std::string > name
jb::config_attribute< thread_config, std::string > scheduler
jb::config_attribute< thread_config, std::string > priority
jb::config_attribute< thread_config, int > affinity
Additional Inherited Members
Static Protected Member Functions inherited from jb::config_object
static attribute_descriptor desc (std::string const &name)
Convenience function to create attribute descriptors with less typing.
static attribute_descriptor desc (std::string const &name, std::string const &class_name)
Convenience function to create attribute descriptors with less typing.
Detailed Description
A configuration class for threads.
Definition at line 15 of file configuration.cpp.
Constructor & Destructor Documentation
thread_config()
thread_config::thread_config () inline
Definition at line 19 of file configuration.cpp.
References config_object_constructors().
Member Function Documentation
config_object_constructors()
thread_config::config_object_constructors (thread_config)
Referenced by thread_config(), and worker_config::worker_config().
native_priority()
int thread_config::native_priority () const
Definition at line 143 of file configuration.cpp.
References native_scheduling_policy(), priority, and jb::strtonum().
native_scheduling_policy()
int thread_config::native_scheduling_policy () const
Definition at line 122 of file configuration.cpp.
References scheduler.
Referenced by native_priority().
Member Data Documentation
affinity
jb::config_attribute<thread_config, int> thread_config::affinity
Definition at line 35 of file configuration.cpp.
name
jb::config_attribute<thread_config, std::string> thread_config::name
Definition at line 31 of file configuration.cpp.
priority
jb::config_attribute<thread_config, std::string> thread_config::priority
Definition at line 33 of file configuration.cpp.
Referenced by native_priority().
scheduler
jb::config_attribute<thread_config, std::string> thread_config::scheduler
Definition at line 32 of file configuration.cpp.
Referenced by native_scheduling_policy().
The documentation for this class was generated from the following file:
examples/configuration.cpp