JayBeams: jb::tde::reduce_sum< T > Class Template Reference
jb::tde::reduce_sum< T > Class Template Reference
Public Member Functions
reduce_sum (std::size_t size, boost::compute::command_queue const &queue)
Public Member Functions inherited from jb::tde::generic_reduce< reduce_sum< T >, T, T >
generic_reduce (std::size_t size, boost::compute::command_queue const &queue)
Constructor.
boost::compute::future< vector_iterator > execute (boost::compute::vector< input_type > const &src, boost::compute::wait_list const &wait=boost::compute::wait_list())
Schedule the execution of a reduction.
Static Public Member Functions
static std::string initialize_body (char const *lhs)
static std::string transform_body (char const *lhs, char const *value, char const *)
static std::string combine_body (char const *accumulated, char const *value)
Static Public Member Functions inherited from jb::tde::generic_reduce< reduce_sum< T >, T, T >
static boost::compute::program create_program (boost::compute::command_queue const &queue)
Additional Inherited Members
Public Types inherited from jb::tde::generic_reduce< reduce_sum< T >, T, T >
using input_type = T
The host type used to represent the input into the reduction.
using output_type = T
The host type representing the output of the reduction.
using vector_iterator = typename boost::compute::vector< input_type >::iterator
The type of the vector used to store the results.
Detailed Description
template<typename T>
class jb::tde::reduce_sum< T >
Definition at line 23 of file ut_generic_reduce.cpp.
Constructor & Destructor Documentation
template<typename T> jb::tde::reduce_sum< T >::reduce_sum (std::size_t size, boost::compute::command_queue const & queue) inline
Definition at line 25 of file ut_generic_reduce.cpp.
Member Function Documentation
template<typename T> static std::string jb::tde::reduce_sum< T >::combine_body (char const * accumulated, char const * value) inline static
Returns
the body of the combine function
Definition at line 41 of file ut_generic_reduce.cpp.
References jb::testing::close_enough(), jb::testing::create_random_timeseries(), jb::opencl::device_selector(), jb::tde::generic_reduce< reduce_sum< T >, T, T >::execute(), JB_LOG, jb::testing::defaults::size, and jb::trace.
template<typename T> static std::string jb::tde::reduce_sum< T >::initialize_body (char const * lhs) inline static
Returns
the body of the initialization function
Definition at line 30 of file ut_generic_reduce.cpp.
template<typename T> static std::string jb::tde::reduce_sum< T >::transform_body (char const * lhs, char const * value, char const *) inline static
Returns
the body of the transform function
Definition at line 36 of file ut_generic_reduce.cpp.
The documentation for this class was generated from the following file:
jb/tde/ut_generic_reduce.cpp