JayBeams: jb::config_object Class Reference
jb::config_object Class Reference
Base class for all configuration objects.
#include <config_object.hpp>
Classes
class attribute_base
Define the interface to manipulate and access configuration attributes embedded in a config_object.
struct attribute_descriptor
An attribute descriptor.
Public Member Functions
config_object ()
Default constructor.
config_object (config_object const &rhs)
Copy constructor.
config_object (config_object &&rhs)
Move constructor.
virtual ~config_object ()
Destructor.
config_object & operator= (config_object rhs)
Copy & swap assignment.
void swap (config_object &rhs)
Derived classes should implement member by member swap.
void load_overrides (int &argc, char *argv[], std::string const &filename, char const *environment_variable_name)
Read the configuration file and load the overrides defined therein.
void load_overrides (int &argc, char *argv[], std::string const &filename)
Read the configuration file and load the overrides defined therein.
void load_overrides (int &argc, char *argv[], std::istream &is)
Read the configuration file and load the overrides defined therein.
void process_cmdline (int &argc, char *argv[])
Process the command line.
virtual void validate () const
Validate the settings.
std::ostream & to_stream (std::ostream &os) const
Print out the settings.
Static Protected Member Functions
static attribute_descriptor desc (std::string const &name)
Convenience function to create attribute descriptors with less typing.
static attribute_descriptor desc (std::string const &name, std::string const &class_name)
Convenience function to create attribute descriptors with less typing.
Private Member Functions
void apply_overrides (YAML::Node const &by_name)
Apply the overrides contained in the YAML document, compute the initial by_class overrides.
void apply_overrides (YAML::Node const &by_name, class_overrides const &by_class)
Apply the overrides contained in the YAML document.
void auto_register (attribute_base *a)
void validate_attributes () const
Run validate() on each attribute contained by this config_object.
void validate_all () const
void add_options (boost::program_options::options_description &options, std::string const &prefix, attribute_descriptor const &d) const
Add the attributes of this config_object as command-line options.
void apply_cmdline_values (boost::program_options::variables_map const &vm, std::string const &prefix)
Apply the values from the cmdline to this configuration object.
YAML::Node to_yaml () const
Print out the configuration settings in YAML format.
Static Private Member Functions
static std::string cmdline_arg_name (std::string const &prefix, std::string const &name)
Compute the full name of a command-line argument, given its prefix and short name.
Private Attributes
std::vector< attribute_base * > attributes_
The list of attributes.
Friends
class generic_config_attribute
struct config_recurse
Validate both the config_object and each attribute.
Detailed Description
Base class for all configuration objects.
A configuration object is a class derived from jb::config_object and having only members of jb::config_attribute type. Configuration objects can read overrides to their defaults from a YAML file.
Please
See also
listing:examples:configurations for some examples.
Definition at line 30 of file config_object.hpp.
Constructor & Destructor Documentation
config_object() [1/3]
jb::config_object::config_object ()
Default constructor.
Derived classes should initialize all their member attributes to their default values.
Definition at line 27 of file config_object.cpp.
config_object() [2/3]
jb::config_object::config_object (config_object const & rhs) inline
Copy constructor.
Derived classes should implement member-by-member copying using the config_attribute(container*, config_attribute const&) constructor.
Definition at line 50 of file config_object.hpp.
config_object() [3/3]
jb::config_object::config_object (config_object && rhs) inline
Move constructor.
Derived classes should implement member-by-member move using the config_attribute(container*, config_attribute&&) constructor.
Definition at line 60 of file config_object.hpp.
~config_object()
virtual jb::config_object::~config_object () inline virtual
Destructor.
Definition at line 65 of file config_object.hpp.
Member Function Documentation
add_options()
void jb::config_object::add_options (boost::program_options::options_description & options, std::string const & prefix, attribute_descriptor const & d) const private
Add the attributes of this config_object as command-line options.
Definition at line 146 of file config_object.cpp.
References attributes_, and jb::config_object::attribute_descriptor::helpmsg.
Referenced by jb::config_object::attribute_base::attribute_base(), and process_cmdline().
apply_cmdline_values()
void jb::config_object::apply_cmdline_values (boost::program_options::variables_map const & vm, std::string const & prefix) private
Apply the values from the cmdline to this configuration object.
Definition at line 157 of file config_object.cpp.
References attributes_, and cmdline_arg_name().
Referenced by jb::config_object::attribute_base::attribute_base(), and process_cmdline().
apply_overrides() [1/2]
void jb::config_object::apply_overrides (YAML::Node const & by_name) private
Apply the overrides contained in the YAML document, compute the initial by_class overrides.
Parameters
by_name a YAML document describing what values (and classes) to override.
Definition at line 77 of file config_object.cpp.
References jb::yaml::merge().
Referenced by jb::config_object::attribute_base::attribute_base(), desc(), and load_overrides().
apply_overrides() [2/2]
void jb::config_object::apply_overrides (YAML::Node const & by_name, class_overrides const & by_class) private
Apply the overrides contained in the YAML document.
Parameters
by_name a YAML document describing what values (and classes) to override.
by_class the set of per-class overrides to apply
Definition at line 83 of file config_object.cpp.
References attributes_, jb::yaml::clone(), and jb::yaml::merge().
auto_register()
void jb::config_object::auto_register (attribute_base * a) private
Definition at line 164 of file config_object.cpp.
References attributes_.
Referenced by jb::config_object::attribute_base::attribute_base().
cmdline_arg_name()
std::string jb::config_object::cmdline_arg_name (std::string const & prefix, std::string const & name) static private
Compute the full name of a command-line argument, given its prefix and short name.
Parameters
prefix the prefix for the argument
name the name of the argument
Definition at line 179 of file config_object.cpp.
Referenced by jb::config_recurse::add_options(), jb::config_recurse::apply_cmdline_values(), apply_cmdline_values(), and desc().
desc() [1/2]
static attribute_descriptor jb::config_object::desc (std::string const & name) inline static protected
Convenience function to create attribute descriptors with less typing.
Definition at line 240 of file config_object.hpp.
References jb::config_object::attribute_descriptor::attribute_descriptor().
Referenced by main().
desc() [2/2]
static attribute_descriptor jb::config_object::desc (std::string const & name, std::string const & class_name) inline static protected
Convenience function to create attribute descriptors with less typing.
Definition at line 246 of file config_object.hpp.
References apply_overrides(), jb::config_object::attribute_descriptor::attribute_descriptor(), cmdline_arg_name(), and jb::config_object::attribute_descriptor::name.
load_overrides() [1/3]
void jb::config_object::load_overrides (int & argc, char * argv[], std::string const & filename, char const * environment_variable_name)
Read the configuration file and load the overrides defined therein.
Find the correct configuration file to load using jb::config_files_locations, then load the configuration file and apply the overrides from that file.
Parameters
argc the number of command-line arguments
argv the command-line arguments
filename the basename of the file to load
environment_variable_name the name of the *_ROOT to use when searching for the configuration file.
Definition at line 31 of file config_object.cpp.
References jb::debug, JB_LOG, process_cmdline(), and jb::warning.
Referenced by BOOST_AUTO_TEST_CASE(), load_overrides(), main(), and swap().
load_overrides() [2/3]
void jb::config_object::load_overrides (int & argc, char * argv[], std::string const & filename)
Read the configuration file and load the overrides defined therein.
Find the correct configuration file to load using jb::config_files_locations, then load the configuration file and apply the overrides from that file.
Parameters
argc the number of command-line arguments
argv the command-line arguments
filename the basename of the file to load
Definition at line 51 of file config_object.cpp.
References jb::debug, JB_LOG, load_overrides(), process_cmdline(), and jb::warning.
load_overrides() [3/3]
void jb::config_object::load_overrides (int & argc, char * argv[], std::istream & is)
Read the configuration file and load the overrides defined therein.
Find the correct configuration file to load using jb::config_files_locations, then load the configuration file and apply the overrides from that file.
Parameters
argc the number of command-line arguments
argv the command-line arguments
is the stream to load the configuration from.
Definition at line 70 of file config_object.cpp.
References apply_overrides(), and process_cmdline().
operator=()
config_object& jb::config_object::operator= (config_object rhs) inline
Copy & swap assignment.
Definition at line 71 of file config_object.hpp.
References swap().
process_cmdline()
void jb::config_object::process_cmdline (int & argc, char * argv[])
Process the command line.
Definition at line 103 of file config_object.cpp.
References add_options(), apply_cmdline_values(), attributes_, and validate_all().
Referenced by BOOST_AUTO_TEST_CASE(), load_overrides(), main(), and swap().
swap()
void jb::config_object::swap (config_object & rhs) inline
Derived classes should implement member by member swap.
Definition at line 79 of file config_object.hpp.
References load_overrides(), process_cmdline(), to_stream(), and validate().
Referenced by operator=().
to_stream()
std::ostream & jb::config_object::to_stream (std::ostream & os) const
Print out the settings.
Definition at line 141 of file config_object.cpp.
References to_yaml().
Referenced by jb::operator<<(), and swap().
to_yaml()
YAML::Node jb::config_object::to_yaml () const private
Print out the configuration settings in YAML format.
Definition at line 190 of file config_object.cpp.
References attributes_.
Referenced by jb::config_object::attribute_base::attribute_base(), and to_stream().
validate()
void jb::config_object::validate () const virtual
Validate the settings.
Exceptions
jb::usage if a problem is detected.
Reimplemented in jb::offline_feed_statistics::config, jb::itch5::array_based_order_book::config, jb::book_depth_statistics::config, jb::log::config, jb::itch5::map_based_order_book::config, and jb::itch5::mold_udp_pacer_config.
Definition at line 138 of file config_object.cpp.
Referenced by jb::config_object::attribute_base::attribute_base(), swap(), and validate_all().
validate_all()
void jb::config_object::validate_all () const private
Definition at line 168 of file config_object.cpp.
References validate(), and validate_attributes().
Referenced by process_cmdline().
validate_attributes()
void jb::config_object::validate_attributes () const private
Run validate() on each attribute contained by this config_object.
Definition at line 173 of file config_object.cpp.
References attributes_.
Referenced by validate_all().
Friends And Related Function Documentation
config_recurse
friend struct config_recurse friend
Validate both the config_object and each attribute.
Definition at line 287 of file config_object.hpp.
generic_config_attribute
friend class generic_config_attribute friend
Definition at line 280 of file config_object.hpp.
Member Data Documentation
attributes_
std::vector<attribute_base*> jb::config_object::attributes_ private
The list of attributes.
Definition at line 309 of file config_object.hpp.
Referenced by add_options(), apply_cmdline_values(), apply_overrides(), auto_register(), process_cmdline(), to_yaml(), and validate_attributes().
The documentation for this class was generated from the following files:
jb/config_object.hpp
jb/config_object.cpp