JayBeams: jb::integer_range_binning< sample_type_t > Class Template Reference
jb::integer_range_binning< sample_type_t > Class Template Reference
A histogram binning_strategy for integer numbers in a known range.
#include <integer_range_binning.hpp>
Public Types
typedef sample_type_t sample_type
type traits as required by binning_strategy_concept
Public Member Functions
integer_range_binning (sample_type h_min, sample_type h_max)
Constructor based on the histogram range.
Implement binning_strategy_concept interface.
Please see binning_strategy_concept for detailed documentation of each member function.
sample_type histogram_min () const
sample_type histogram_max () const
sample_type theoretical_min () const
sample_type theoretical_max () const
std::size_t sample2bin (sample_type t) const
sample_type bin2sample (std::size_t i) const
sample_type interpolate (sample_type x_a, sample_type x_b, double y_a, double s, double q) const
Private Attributes
sample_type h_min_
sample_type h_max_
Detailed Description
template<typename sample_type_t>
class jb::integer_range_binning< sample_type_t >
A histogram binning_strategy for integer numbers in a known range.
This class defines histogram bins for samples with integer values in a range defined at run-time. Care must be taken if the range is too big because the corresponding histogram is likely to consume a lot of memory. See jb::binning_strategy_concept.
Template Parameters:
sample_type_t the type of samples, should be an integer type.
Definition at line 22 of file integer_range_binning.hpp.
Member Typedef Documentation
template<typename sample_type_t > typedef sample_type_t jb::integer_range_binning< sample_type_t >::sample_type
type traits as required by binning_strategy_concept
Definition at line 25 of file integer_range_binning.hpp.
Constructor & Destructor Documentation
template<typename sample_type_t > jb::integer_range_binning< sample_type_t >::integer_range_binning (sample_type h_min, sample_type h_max) [inline]
Constructor based on the histogram range.
Parameters:
h_min The value for histogram_min()
h_max The value for histogram_max()
Definition at line 33 of file integer_range_binning.hpp.
Member Function Documentation
template<typename sample_type_t > sample_type jb::integer_range_binning< sample_type_t >::bin2sample (std::size_t i) const [inline]
Definition at line 63 of file integer_range_binning.hpp.
References jb::integer_range_binning< sample_type_t >::histogram_min().
template<typename sample_type_t > sample_type jb::integer_range_binning< sample_type_t >::histogram_max () const [inline]
Definition at line 51 of file integer_range_binning.hpp.
References jb::integer_range_binning< sample_type_t >::h_max_.
template<typename sample_type_t > sample_type jb::integer_range_binning< sample_type_t >::histogram_min () const [inline]
Definition at line 48 of file integer_range_binning.hpp.
References jb::integer_range_binning< sample_type_t >::h_min_.
Referenced by jb::integer_range_binning< sample_type_t >::bin2sample(), and jb::integer_range_binning< sample_type_t >::sample2bin().
template<typename sample_type_t > sample_type jb::integer_range_binning< sample_type_t >::interpolate (sample_type x_a, sample_type x_b, double y_a, double s, double q) const [inline]
Definition at line 66 of file integer_range_binning.hpp.
References jb::histogram_binning_linear_interpolation().
template<typename sample_type_t > std::size_t jb::integer_range_binning< sample_type_t >::sample2bin (sample_type t) const [inline]
Definition at line 60 of file integer_range_binning.hpp.
References jb::integer_range_binning< sample_type_t >::histogram_min().
template<typename sample_type_t > sample_type jb::integer_range_binning< sample_type_t >::theoretical_max () const [inline]
Definition at line 57 of file integer_range_binning.hpp.
template<typename sample_type_t > sample_type jb::integer_range_binning< sample_type_t >::theoretical_min () const [inline]
Definition at line 54 of file integer_range_binning.hpp.
Member Data Documentation
template<typename sample_type_t > sample_type jb::integer_range_binning< sample_type_t >::h_max_ [private]
Definition at line 74 of file integer_range_binning.hpp.
Referenced by jb::integer_range_binning< sample_type_t >::histogram_max().
template<typename sample_type_t > sample_type jb::integer_range_binning< sample_type_t >::h_min_ [private]
Definition at line 73 of file integer_range_binning.hpp.
Referenced by jb::integer_range_binning< sample_type_t >::histogram_min().
The documentation for this class was generated from the following file:
jb/integer_range_binning.hpp