JayBeams: jb::testing::microbenchmark< Fixture > Class Template Reference
jb::testing::microbenchmark< Fixture > Class Template Reference
Run a micro-benchmark on a given class.
#include <microbenchmark.hpp>
Public Types
typedef jb::testing::microbenchmark_config config
Public Types inherited from jb::testing::microbenchmark_base
typedef std::chrono::steady_clock clock
typedef clock::duration duration
typedef std::pair< int, duration > result
typedef std::vector< result > results
Public Member Functions
microbenchmark ()
Default constructor, create a default configuration and initialize from it.
microbenchmark (config const &cfg)
Constructor from a configuration.
template<typename... Args>
results run (Args &&...args)
Run the microbenchmaark.
Public Member Functions inherited from jb::testing::microbenchmark_base
microbenchmark_base (microbenchmark_config const &cfg)
Constructor from a configuration.
void write_results (std::ostream &os, results const &r) const
Private Member Functions
template<typename... Args>
results run_unsized (Args &&...args)
Run a test without specifying the size and some additional arguments for the Fixture constructor.
results run_unsized ()
Run a test without specifying the size and no additional arguments for the Fixture constructor.
template<typename... Args>
results run_fixed_size (Args &&...args)
Run the test when the size is specified in the microbenchmark configuration.
template<typename... Args>
void run_sized (int size, results &r, Args &&...args)
Construct a fixture for the given size and run the microbenchmkark.
void run_base (Fixture &fixture, results &r, int size)
Run a microbenchmkark for a constructed fixture.
Static Private Member Functions
static void run_iteration (Fixture &fixture, results &r, int size)
Run a single iteration of the test and return the results.
Additional Inherited Members
Protected Attributes inherited from jb::testing::microbenchmark_base
microbenchmark_config config_
Detailed Description
template<typename Fixture>
class jb::testing::microbenchmark< Fixture >
Run a micro-benchmark on a given class.
This class is used to run microbenchmarks. To use it, you wrap your function or class in a Fixture that constructs the unit under test and calls it. For example, consider a class like this:
class Foo {
public:
  Foo(std::string const& need_one_string);
  std::string bar(std::string const& need_another_string);
};
To thest the bar() function you would create a Fixture class like this:
class FooBarFixture {
public:
  FooBarFixture(std::string const& pass_on)
    : foo_(pass_on), input_string_("some value") {}
  void run() const {
    foo_.bar(input_string_);
  }
private:
  Foo foo_;
  std::string input_string_;
};
Then you can run the test using:
jb::testing::microbenchmark<FooBarFixture> mb(jb::microbenchmark_config());
auto results = mb.run(std::string("some other value");
jb::microbenchmark_base::summary summary(results);
std::cout << summary; // or something more clever...
// for a full dump: mb.write_results(std::cout, results);
The framework creates a single instance of the Fixture for the full test, it worries about running a warmup iteration, collecting the results with minimal overhead, and creating a sensible summary.
Template Parameters
Fixture A type meeting the following requirements:
class Fixture {
public:
  Fixture(Args ...); // default constructor, used for the default sized test
  Fixture(int s, Args ...); // constructor for a test of size 's'
  void run(); // run one iteration of the test
};
Definition at line 69 of file microbenchmark.hpp.
Member Typedef Documentation
template<typename Fixture> typedef jb::testing::microbenchmark_config jb::testing::microbenchmark< Fixture >::config
Definition at line 71 of file microbenchmark.hpp.
Constructor & Destructor Documentation
template<typename Fixture> jb::testing::microbenchmark< Fixture >::microbenchmark () inline
Default constructor, create a default configuration and initialize from it.
Definition at line 77 of file microbenchmark.hpp.
template<typename Fixture> jb::testing::microbenchmark< Fixture >::microbenchmark (config const & cfg) inline explicit
Constructor from a configuration.
Definition at line 84 of file microbenchmark.hpp.
Member Function Documentation
template<typename Fixture> template<typename... Args> results jb::testing::microbenchmark< Fixture >::run (Args &&... args) inline
Run the microbenchmaark.
Parameters
args the additional arguments, if any, for the Fixture constructor.
Template Parameters
Args the types for the additional arguments.
Definition at line 97 of file microbenchmark.hpp.
References jb::testing::microbenchmark_base::config_, jb::testing::microbenchmark< Fixture >::run_fixed_size(), jb::testing::microbenchmark< Fixture >::run_unsized(), and jb::testing::microbenchmark_config::size.
template<typename Fixture> void jb::testing::microbenchmark< Fixture >::run_base (Fixture & fixture, results & r, int size) inline private
Run a microbenchmkark for a constructed fixture.
Run the warmup iterations and then run the actual iterations for the test. The results of the test are ignored during the warmup phase.
Parameters
fixture the object under test
r where to store the results of the test
size the size of the test
Definition at line 170 of file microbenchmark.hpp.
References jb::testing::microbenchmark_base::config_, jb::testing::microbenchmark_config::iterations, jb::testing::microbenchmark< Fixture >::run_iteration(), and jb::testing::microbenchmark_config::warmup_iterations.
Referenced by jb::testing::microbenchmark< Fixture >::run_sized(), and jb::testing::microbenchmark< Fixture >::run_unsized().
template<typename Fixture> template<typename... Args> results jb::testing::microbenchmark< Fixture >::run_fixed_size (Args &&... args) inline private
Run the test when the size is specified in the microbenchmark configuration.
Parameters
args additional arguments for the Fixture
Template Parameters
Args the types for the additional arguments
Definition at line 139 of file microbenchmark.hpp.
References jb::testing::microbenchmark_base::config_, jb::testing::microbenchmark< Fixture >::run_sized(), and jb::testing::microbenchmark_config::size.
Referenced by jb::testing::microbenchmark< Fixture >::run().
template<typename Fixture> static void jb::testing::microbenchmark< Fixture >::run_iteration (Fixture & fixture, results & r, int size) inline static private
Run a single iteration of the test and return the results.
Parameters
fixture the object under test
r where to store the results of the test
size the size of the test
Definition at line 188 of file microbenchmark.hpp.
Referenced by jb::testing::microbenchmark< Fixture >::run_base().
template<typename Fixture> template<typename... Args> void jb::testing::microbenchmark< Fixture >::run_sized (int size, results & r, Args &&... args) inline private
Construct a fixture for the given size and run the microbenchmkark.
Parameters
size the size of the test
r where to store the results of the test
args additional arguments for the constructor, if any.
Template Parameters
Args the types of the additional arguments, if any.
Definition at line 154 of file microbenchmark.hpp.
References jb::testing::microbenchmark< Fixture >::run_base().
Referenced by jb::testing::microbenchmark< Fixture >::run_fixed_size().
template<typename Fixture> template<typename... Args> results jb::testing::microbenchmark< Fixture >::run_unsized (Args &&... args) inline private
Run a test without specifying the size and some additional arguments for the Fixture constructor.
Parameters
args additional arguments for the Fixture
Template Parameters
Args the types for the additional arguments
Definition at line 113 of file microbenchmark.hpp.
References jb::testing::microbenchmark< Fixture >::run_base().
template<typename Fixture> results jb::testing::microbenchmark< Fixture >::run_unsized () inline private
Run a test without specifying the size and no additional arguments for the Fixture constructor.
Definition at line 124 of file microbenchmark.hpp.
References jb::testing::microbenchmark< Fixture >::run_base().
Referenced by jb::testing::microbenchmark< Fixture >::run().
The documentation for this class was generated from the following file:
jb/testing/microbenchmark.hpp