The JayBeams Library: jb::config_files_locations< getenv_functor, validator_functor > Class Template Reference
jb::config_files_locations< getenv_functor, validator_functor > Class Template Reference
Compute the directories where a configuration file can be found.
#include <config_files_location.hpp>
Public Member Functions
config_files_locations (boost::filesystem::path const &argv0, char const *program_root_variable, getenv_functor getenv)
Constructor.
config_files_locations (boost::filesystem::path const &argv0, getenv_functor getenv)
Constructor.
boost::filesystem::path find_configuration_file (std::string const &filename, validator_functor validator) const
Find a configuration file in the computed search path.
boost::filesystem::path find_configuration_file (std::string const &filename) const
Find a configuration file in the computed search path.
config_files_locations (boost::filesystem::path const &argv0, char const *program_root_variable)
Convenience constructors.
config_files_locations (boost::filesystem::path const &argv0)
config_files_locations (char const *argv0, char const *program_root_variable, getenv_functor getenv)
config_files_locations (char const *argv0, char const *program_root_variable)
config_files_locations (char const *argv0, getenv_functor getenv)
config_files_locations (char const *argv0)
Detailed Description
template<typename getenv_functor = default_getenv, typename validator_functor = default_validator>
class jb::config_files_locations< getenv_functor, validator_functor >
Compute the directories where a configuration file can be found.
JayBeams configuration files can be located in multiple places: # Each program defines its own '*_ROOT' environment variable, the files are searched there if the variable is defined, otherwise # the files are found in the generic 'JAYBEAMS_ROOT' location, if that environment variable is defined, otherwise # the files are found in the installation directory, if the directory exists, otherwise, # the files are found relative to the program path name.
This class implements the algorithms to (a) compute the valid list of directories for a given program, and (b) select which configuration file to load.
We use some template parameters for dependency injection, it is hard to test the interaction with the file system (and the environment variables) without them.
Template Parameters:
getenv_functor the functor used to fetch the value of environment variables. This is used for dependency injection during testing.
validator_functor the functor used to validate if a given path is readable. This is used for dependency injection during testing.
Definition at line 103 of file config_files_location.hpp.
Constructor & Destructor Documentation
template<typename getenv_functor = default_getenv, typename validator_functor = default_validator> jb::config_files_locations< getenv_functor, validator_functor >::config_files_locations (boost::filesystem::path const & argv0, char const * program_root_variable, getenv_functor getenv) [inline]
Constructor.
Build the search path given the program path and the name of its preferred environment variable.
Parameters:
argv0 the program path, typically argv[0] from main()
program_root_variable the name of the preferred environment variable for this program, i.e., its *_ROOT variable.
getenv the functor object to use
Definition at line 116 of file config_files_location.hpp.
template<typename getenv_functor = default_getenv, typename validator_functor = default_validator> jb::config_files_locations< getenv_functor, validator_functor >::config_files_locations (boost::filesystem::path const & argv0, getenv_functor getenv) [inline]
Constructor.
Build the search path given the program path. Used in programs that do not have a preferred *_ROOT environment variable.
Parameters:
argv0 the program path, typically argv[0] from main()
getenv the functor object to use
Definition at line 133 of file config_files_location.hpp.
template<typename getenv_functor = default_getenv, typename validator_functor = default_validator> jb::config_files_locations< getenv_functor, validator_functor >::config_files_locations (boost::filesystem::path const & argv0, char const * program_root_variable) [inline]
Convenience constructors.
Apply common conversions and create functors as needed.
Definition at line 146 of file config_files_location.hpp.
template<typename getenv_functor = default_getenv, typename validator_functor = default_validator> jb::config_files_locations< getenv_functor, validator_functor >::config_files_locations (boost::filesystem::path const & argv0) [inline, explicit]
Definition at line 152 of file config_files_location.hpp.
template<typename getenv_functor = default_getenv, typename validator_functor = default_validator> jb::config_files_locations< getenv_functor, validator_functor >::config_files_locations (char const * argv0, char const * program_root_variable, getenv_functor getenv) [inline]
Definition at line 157 of file config_files_location.hpp.
template<typename getenv_functor = default_getenv, typename validator_functor = default_validator> jb::config_files_locations< getenv_functor, validator_functor >::config_files_locations (char const * argv0, char const * program_root_variable) [inline]
Definition at line 164 of file config_files_location.hpp.
template<typename getenv_functor = default_getenv, typename validator_functor = default_validator> jb::config_files_locations< getenv_functor, validator_functor >::config_files_locations (char const * argv0, getenv_functor getenv) [inline]
Definition at line 170 of file config_files_location.hpp.
template<typename getenv_functor = default_getenv, typename validator_functor = default_validator> jb::config_files_locations< getenv_functor, validator_functor >::config_files_locations (char const * argv0) [inline, explicit]
Definition at line 175 of file config_files_location.hpp.
Member Function Documentation
template<typename getenv_functor = default_getenv, typename validator_functor = default_validator> boost::filesystem::path jb::config_files_locations< getenv_functor, validator_functor >::find_configuration_file (std::string const & filename, validator_functor validator) const [inline]
Find a configuration file in the computed search path.
Parameters:
filename the basename of the configuration file.
validator the functor to use for validation
Returns:
the path to load
Exceptions:
std::runtime_error if no suitable file was found.
Definition at line 191 of file config_files_location.hpp.
References jb::config_files_locations_base::search_path().
Referenced by jb::config_files_locations< getenv_functor, validator_functor >::find_configuration_file(), and jb::config_object::load_overrides().
template<typename getenv_functor = default_getenv, typename validator_functor = default_validator> boost::filesystem::path jb::config_files_locations< getenv_functor, validator_functor >::find_configuration_file (std::string const & filename) const [inline]
Find a configuration file in the computed search path.
Parameters:
filename the basename of the configuration file.
Returns:
the path to load
Exceptions:
std::runtime_error if no suitable file was found.
Definition at line 212 of file config_files_location.hpp.
References jb::config_files_locations< getenv_functor, validator_functor >::find_configuration_file().
The documentation for this class was generated from the following file:
jb/config_files_location.hpp