JayBeams: jb::itch5::unknown_message Class Reference
jb::itch5::unknown_message Class Reference
A simple.
#include <unknown_message.hpp>
Public Member Functions
unknown_message (std::uint32_t count, std::size_t offset, std::size_t len, void const *buf)
Constructor from message details.
unknown_message (unknown_message &&)=default
template<bool validate>
message_header decode_header () const
Extract the message header.
Accessors
std::uint32_t count () const
std::uint64_t offset () const
std::size_t len () const
void const * buf () const
Private Member Functions
unknown_message (unknown_message const &)=delete
unknown_message & operator= (unknown_message const &)=delete
Private Attributes
std::uint32_t count_
std::size_t offset_
std::size_t len_
void const * buf_
Detailed Description
A simple.
Definition at line 12 of file unknown_message.hpp.
Constructor & Destructor Documentation
unknown_message() [1/3]
jb::itch5::unknown_message::unknown_message (std::uint32_t count, std::size_t offset, std::size_t len, void const * buf) inline
Constructor from message details.
Definition at line 15 of file unknown_message.hpp.
Referenced by decode_header().
unknown_message() [2/3]
jb::itch5::unknown_message::unknown_message (unknown_message &&) default
unknown_message() [3/3]
jb::itch5::unknown_message::unknown_message (unknown_message const &) private delete
Member Function Documentation
buf()
void const* jb::itch5::unknown_message::buf () const inline
Definition at line 37 of file unknown_message.hpp.
References buf_.
Referenced by jb::itch5::mold_udp_pacer< clock_type >::coalesce(), decode_header(), jb::itch5::compute_book< book_type >::handle_unknown(), and main().
count()
std::uint32_t jb::itch5::unknown_message::count () const inline
Definition at line 28 of file unknown_message.hpp.
References count_.
Referenced by jb::itch5::mold_udp_pacer< clock_type >::coalesce(), jb::itch5::mold_udp_pacer< clock_type >::handle_message(), jb::itch5::compute_book< book_type >::handle_unknown(), and main().
decode_header()
template<bool validate> message_header jb::itch5::unknown_message::decode_header () const inline
Extract the message header.
Definition at line 44 of file unknown_message.hpp.
References buf(), len(), operator=(), jb::itch5::decoder< validate, T >::r(), and unknown_message().
Referenced by jb::itch5::mold_udp_pacer< clock_type >::handle_message().
len()
std::size_t jb::itch5::unknown_message::len () const inline
Definition at line 34 of file unknown_message.hpp.
References len_.
Referenced by jb::itch5::mold_udp_pacer< clock_type >::coalesce(), and decode_header().
offset()
std::uint64_t jb::itch5::unknown_message::offset () const inline
Definition at line 31 of file unknown_message.hpp.
References offset_.
Referenced by jb::itch5::compute_book< book_type >::handle_unknown(), and main().
operator=()
unknown_message& jb::itch5::unknown_message::operator= (unknown_message const &) private delete
Referenced by decode_header().
Member Data Documentation
buf_
void const* jb::itch5::unknown_message::buf_ private
Definition at line 58 of file unknown_message.hpp.
Referenced by buf().
count_
std::uint32_t jb::itch5::unknown_message::count_ private
Definition at line 55 of file unknown_message.hpp.
Referenced by count().
len_
std::size_t jb::itch5::unknown_message::len_ private
Definition at line 57 of file unknown_message.hpp.
Referenced by len().
offset_
std::size_t jb::itch5::unknown_message::offset_ private
Definition at line 56 of file unknown_message.hpp.
Referenced by offset().
The documentation for this class was generated from the following file:
jb/itch5/unknown_message.hpp