JayBeams: jb::config_attribute< C, T > Class Template Reference
jb::config_attribute< C, T > Class Template Reference
Helper class to easily define configuration attributes.
#include <config_attribute.hpp>
Public Types
typedef C container_type
typedef T value_type
Public Member Functions
void swap (config_attribute< container_type, value_type > &rhs)
Swap values, containers are not changed.
value_type const & operator() () const
Accessor.
container_type & operator() (value_type const &x)
Modify value.
container_type & operator() (value_type &&x)
Modify value with move semantics.
Public Member Functions inherited from jb::config_object::attribute_base
virtual ~attribute_base ()=0
Destructor.
attribute_descriptor const & descriptor () const
std::string const & name () const
std::string const & class_name () const
std::string const & help () const
bool positional () const
Private Member Functions
Configuration object recursion functions.
void apply_overrides (YAML::Node const &by_name, class_overrides const &by_class) override
Call the right version of jb::apply_overrides for the contained value.
void add_options (boost::program_options::options_description &options, std::string const &prefix, config_object::attribute_descriptor const &d) const override
Call the right version of jb::add_options for the contained value.
void apply_cmdline_values (boost::program_options::variables_map const &vm, std::string const &name) override
Call the right version of jb::apply_cmdline_values.
void validate () const override
Call the right version of jb::validate.
YAML::Node to_yaml () const override
Print out the configuration settings in YAML format.
Private Attributes
container_type *const container_
value_type value_
Friends
struct config_recurse
Constructors
friend container_type
config_attribute (container_type *container)
config_attribute (config_object::attribute_descriptor const &d, container_type *container)
config_attribute (container_type *container, value_type const &t)
config_attribute (config_object::attribute_descriptor const &d, container_type *container, value_type const &t)
config_attribute (container_type *container, value_type &&t)
config_attribute (config_object::attribute_descriptor const &d, container_type *container, value_type &&t)
template<typename... Args>
config_attribute (container_type *container, Args &&...args)
template<typename... Args>
config_attribute (config_object::attribute_descriptor const &d, container_type *container, Args &&...args)
config_attribute (container_type *container, config_attribute< container_type, value_type > &&rhs)
config_attribute (container_type *container, config_attribute< container_type, value_type > const &rhs)
config_attribute (config_attribute< container_type, value_type > &&)=delete
config_attribute (config_attribute< container_type, value_type > const &)=delete
config_attribute & operator= (config_attribute< container_type, value_type > &&rhs)
config_attribute & operator= (config_attribute< container_type, value_type > const &rhs)
Additional Inherited Members
Protected Member Functions inherited from jb::config_object::attribute_base
attribute_base (attribute_descriptor const &d, config_object *container)
Constructor.
template<typename container_type >
attribute_base (container_type *)
Detailed Description
template<typename C, typename T>
class jb::config_attribute< C, T >
Helper class to easily define configuration attributes.
The Jaybeams configuration framework requires all configuration objects to define accessors and modifiers for each attribute that follow this pattern:
class Config {
public:
 Config(); // default constructor sets to compile-time defaults.
 int attribute() const; // return current attribute value
 Config& attribute(int x); // set current value, chainable
};
Config cfg;
cfg.attribute(1).another(2);
This is a helper class to create such attributes easily.
Template Parameters
C the type of the object that contains the attribute
T the type of the object contained in this attribute
Definition at line 54 of file config_attribute.hpp.
Member Typedef Documentation
template<typename C, typename T> typedef C jb::config_attribute< C, T >::container_type
Definition at line 56 of file config_attribute.hpp.
template<typename C, typename T> typedef T jb::config_attribute< C, T >::value_type
Definition at line 57 of file config_attribute.hpp.
Constructor & Destructor Documentation
template<typename C, typename T> jb::config_attribute< C, T >::config_attribute (container_type * container) inline explicit private
Definition at line 89 of file config_attribute.hpp.
Referenced by jb::config_attribute< jb::testing::microbenchmark_config, bool >::config_attribute().
template<typename C, typename T> jb::config_attribute< C, T >::config_attribute (config_object::attribute_descriptor const & d, container_type * container) inline private
Definition at line 94 of file config_attribute.hpp.
template<typename C, typename T> jb::config_attribute< C, T >::config_attribute (container_type * container, value_type const & t) inline private
Definition at line 101 of file config_attribute.hpp.
template<typename C, typename T> jb::config_attribute< C, T >::config_attribute (config_object::attribute_descriptor const & d, container_type * container, value_type const & t) inline private
Definition at line 107 of file config_attribute.hpp.
template<typename C, typename T> jb::config_attribute< C, T >::config_attribute (container_type * container, value_type && t) inline private
Definition at line 115 of file config_attribute.hpp.
template<typename C, typename T> jb::config_attribute< C, T >::config_attribute (config_object::attribute_descriptor const & d, container_type * container, value_type && t) inline private
Definition at line 121 of file config_attribute.hpp.
template<typename C, typename T> template<typename... Args> jb::config_attribute< C, T >::config_attribute (container_type * container, Args &&... args) inline private
Definition at line 130 of file config_attribute.hpp.
template<typename C, typename T> template<typename... Args> jb::config_attribute< C, T >::config_attribute (config_object::attribute_descriptor const & d, container_type * container, Args &&... args) inline private
Definition at line 137 of file config_attribute.hpp.
template<typename C, typename T> jb::config_attribute< C, T >::config_attribute (container_type * container, config_attribute< container_type, value_type > && rhs) inline private
Definition at line 145 of file config_attribute.hpp.
template<typename C, typename T> jb::config_attribute< C, T >::config_attribute (container_type * container, config_attribute< container_type, value_type > const & rhs) inline private
Definition at line 153 of file config_attribute.hpp.
template<typename C, typename T> jb::config_attribute< C, T >::config_attribute (config_attribute< container_type, value_type > &&) private delete
template<typename C, typename T> jb::config_attribute< C, T >::config_attribute (config_attribute< container_type, value_type > const &) private delete
Member Function Documentation
template<typename C, typename T> void jb::config_attribute< C, T >::add_options (boost::program_options::options_description & options, std::string const & prefix, config_object::attribute_descriptor const & d) const inline override private virtual
Call the right version of jb::add_options for the contained value.
Implements jb::config_object::attribute_base.
Definition at line 189 of file config_attribute.hpp.
template<typename C, typename T> void jb::config_attribute< C, T >::apply_cmdline_values (boost::program_options::variables_map const & vm, std::string const & name) inline override private virtual
Call the right version of jb::apply_cmdline_values.
Implements jb::config_object::attribute_base.
Definition at line 197 of file config_attribute.hpp.
Referenced by jb::config_recurse::apply_cmdline_values().
template<typename C, typename T> void jb::config_attribute< C, T >::apply_overrides (YAML::Node const & by_name, class_overrides const & by_class) inline override private virtual
Call the right version of jb::apply_overrides for the contained value.
Implements jb::config_object::attribute_base.
Definition at line 183 of file config_attribute.hpp.
Referenced by jb::config_recurse::apply_overrides().
template<typename C, typename T> value_type const& jb::config_attribute< C, T >::operator() () const inline
Accessor.
Definition at line 65 of file config_attribute.hpp.
template<typename C, typename T> container_type& jb::config_attribute< C, T >::operator() (value_type const & x) inline
Modify value.
Definition at line 70 of file config_attribute.hpp.
template<typename C, typename T> container_type& jb::config_attribute< C, T >::operator() (value_type && x) inline
Modify value with move semantics.
Definition at line 76 of file config_attribute.hpp.
template<typename C, typename T> config_attribute& jb::config_attribute< C, T >::operator= (config_attribute< container_type, value_type > && rhs) inline private
Definition at line 166 of file config_attribute.hpp.
template<typename C, typename T> config_attribute& jb::config_attribute< C, T >::operator= (config_attribute< container_type, value_type > const & rhs) inline private
Definition at line 171 of file config_attribute.hpp.
template<typename C, typename T> void jb::config_attribute< C, T >::swap (config_attribute< container_type, value_type > & rhs) inline
Swap values, containers are not changed.
Definition at line 60 of file config_attribute.hpp.
template<typename C, typename T> YAML::Node jb::config_attribute< C, T >::to_yaml () const inline override private virtual
Print out the configuration settings in YAML format.
Implements jb::config_object::attribute_base.
Definition at line 209 of file config_attribute.hpp.
Referenced by jb::config_recurse::to_yaml().
template<typename C, typename T> void jb::config_attribute< C, T >::validate () const inline override private virtual
Call the right version of jb::validate.
Implements jb::config_object::attribute_base.
Definition at line 204 of file config_attribute.hpp.
Referenced by jb::config_recurse::validate().
Friends And Related Function Documentation
template<typename C, typename T> friend struct config_recurse friend
Definition at line 177 of file config_attribute.hpp.
Member Data Documentation
template<typename C, typename T> container_type* const jb::config_attribute< C, T >::container_ private
Definition at line 215 of file config_attribute.hpp.
Referenced by jb::config_attribute< jb::testing::microbenchmark_config, bool >::operator()().
template<typename C, typename T> friend jb::config_attribute< C, T >::container_type private
Definition at line 88 of file config_attribute.hpp.
template<typename C, typename T> value_type jb::config_attribute< C, T >::value_ private
Definition at line 216 of file config_attribute.hpp.
Referenced by jb::config_attribute< jb::testing::microbenchmark_config, bool >::add_options(), jb::config_attribute< jb::testing::microbenchmark_config, bool >::apply_cmdline_values(), jb::config_attribute< jb::testing::microbenchmark_config, bool >::apply_overrides(), jb::config_attribute< jb::testing::microbenchmark_config, bool >::operator()(), jb::config_attribute< jb::testing::microbenchmark_config, bool >::operator=(), jb::config_attribute< jb::testing::microbenchmark_config, bool >::swap(), jb::config_attribute< jb::testing::microbenchmark_config, bool >::to_yaml(), and jb::config_attribute< jb::testing::microbenchmark_config, bool >::validate().
The documentation for this class was generated from the following file:
jb/config_attribute.hpp