JayBeams: jb::thread_config Class Reference
jb::thread_config Class Reference
Hold the configuration to initialize threads.
#include <thread_config.hpp>
Public Member Functions
thread_config ()
Constructor.
config_object_constructors (thread_config)
int native_scheduling_policy () const
int native_priority () const
Public Member Functions inherited from jb::config_object
config_object ()
Default constructor.
config_object (config_object const &rhs)
Copy constructor.
config_object (config_object &&rhs)
Move constructor.
virtual ~config_object ()
Destructor.
config_object & operator= (config_object rhs)
Copy & swap assignment.
void swap (config_object &rhs)
Derived classes should implement member by member swap.
void load_overrides (int &argc, char *argv[], std::string const &filename, char const *environment_variable_name)
Read the configuration file and load the overrides defined therein.
void load_overrides (int &argc, char *argv[], std::string const &filename)
Read the configuration file and load the overrides defined therein.
void load_overrides (int &argc, char *argv[], std::istream &is)
Read the configuration file and load the overrides defined therein.
void process_cmdline (int &argc, char *argv[])
Process the command line.
virtual void validate () const
Validate the settings.
std::ostream & to_stream (std::ostream &os) const
Print out the settings.
Public Attributes
jb::config_attribute< thread_config, std::string > name
jb::config_attribute< thread_config, std::string > scheduler
jb::config_attribute< thread_config, std::string > priority
jb::config_attribute< thread_config, jb::cpu_set > affinity
jb::config_attribute< thread_config, bool > ignore_setup_errors
Additional Inherited Members
Static Protected Member Functions inherited from jb::config_object
static attribute_descriptor desc (std::string const &name)
Convenience function to create attribute descriptors with less typing.
static attribute_descriptor desc (std::string const &name, std::string const &class_name)
Convenience function to create attribute descriptors with less typing.
Detailed Description
Hold the configuration to initialize threads.
After a thread is started we want to be able to consistently configure its scheduling policy, priority, processor affinity, etc. This class is used to contain such configurations.
Definition at line 16 of file thread_config.hpp.
Constructor & Destructor Documentation
thread_config()
thread_config::thread_config ()
Constructor.
Definition at line 29 of file thread_config.cpp.
Member Function Documentation
config_object_constructors()
jb::thread_config::config_object_constructors (thread_config)
native_priority()
int thread_config::native_priority () const
Definition at line 75 of file thread_config.cpp.
References native_scheduling_policy(), priority, and jb::strtonum().
Referenced by BOOST_AUTO_TEST_CASE(), and jb::detail::reconfigure_this_thread().
native_scheduling_policy()
int thread_config::native_scheduling_policy () const
Definition at line 54 of file thread_config.cpp.
References scheduler.
Referenced by BOOST_AUTO_TEST_CASE(), native_priority(), and jb::detail::reconfigure_this_thread().
Member Data Documentation
affinity
jb::config_attribute<thread_config, jb::cpu_set> jb::thread_config::affinity
Definition at line 25 of file thread_config.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), and jb::detail::reconfigure_this_thread().
ignore_setup_errors
jb::config_attribute<thread_config, bool> jb::thread_config::ignore_setup_errors
Definition at line 26 of file thread_config.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), and jb::detail::reconfigure_this_thread().
name
jb::config_attribute<thread_config, std::string> jb::thread_config::name
Definition at line 22 of file thread_config.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), and jb::detail::reconfigure_this_thread().
priority
jb::config_attribute<thread_config, std::string> jb::thread_config::priority
Definition at line 24 of file thread_config.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), and native_priority().
scheduler
jb::config_attribute<thread_config, std::string> jb::thread_config::scheduler
Definition at line 23 of file thread_config.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), and native_scheduling_policy().
The documentation for this class was generated from the following files:
jb/thread_config.hpp
jb/thread_config.cpp