JayBeams: jb::itch5::compute_inside Class Reference
jb::itch5::compute_inside Class Reference
An implementation of jb::message_handler_concept to compute the inside.
#include <compute_inside.hpp>
Classes
struct order_data
A convenient container for per-order data.
Public Types
Type traits
typedef
std::chrono::steady_clock::time_point time_point
Define the clock used to measure processing delays.
typedef std::function< void(time_point,
message_header const
&, stock_t const &, half_quote
const &, half_quote const &)> callback_type
Callbacks.
Public Member Functions
compute_inside (callback_type const &callback)
Initialize an empty handler.
time_point now () const
Return the current timestamp for delay measurements.
void handle_message (time_point recv_ts, long msgcnt, std::size_t msgoffset, stock_directory_message const &msg)
Pre-populate the books based on the symbol directory.
void handle_message (time_point recv_ts, long msgcnt, std::size_t msgoffset, add_order_message const &msg)
Handle a new order.
void handle_message (time_point recv_ts, long msgcnt, std::size_t msgoffset, add_order_mpid_message const &msg)
Handle a new order with MPID.
void handle_message (time_point recv_ts, long msgcnt, std::size_t msgoffset, order_executed_message const &msg)
Handle an order execution.
void handle_message (time_point recv_ts, long msgcnt, std::size_t msgoffset, order_executed_price_message const &msg)
Handle an order execution.
void handle_message (time_point recv_ts, long msgcnt, std::size_t msgoffset, order_cancel_message const &msg)
Handle a partial cancel.
void handle_message (time_point recv_ts, long msgcnt, std::size_t msgoffset, order_delete_message const &msg)
Handle a full cancel.
void handle_message (time_point recv_ts, long msgcnt, std::size_t msgoffset, order_replace_message const &msg)
Handle an order replace.
template<typename message_type >
void handle_message (time_point recv_ts, long msgcnt, std::size_t msgoffset, message_type const &msg)
Ignore all other message types.
void handle_unknown (time_point recv_ts, unknown_message const &msg)
Log any unknown message types.
std::size_t live_order_count () const
An accessor to make testing easier.
Private Types
typedef std::unordered_map
< std::uint64_t, order_data > orders_by_id
The list of live orders.
typedef std::unordered_map
< stock_t, order_book,
boost::hash< stock_t > > books_by_security
The collection of order books.
typedef std::tuple< bool,
order_data,
books_by_security::iterator > update_result
The result of a reduction is fairly complex ...
Private Member Functions
update_result handle_add_order (time_point recv_ts, long msgcnt, std::size_t msgoffset, add_order_message const &msg)
Refactor handling of add_order_message for both add_order and replace.
void handle_reduce (time_point recv_ts, long msgcnt, std::size_t msgoffset, message_header const &header, std::uint64_t order_reference_number, std::uint32_t shares, bool all_shares)
Handle both order executions and partial cancels.
update_result handle_reduce_no_update (time_point recv_ts, long msgcnt, std::size_t msgoffset, message_header const &header, std::uint64_t order_reference_number, std::uint32_t shares, bool all_shares)
Handle an order reduction, but do not update the callback.
Private Attributes
callback_type callback_
Store the callback ...
orders_by_id orders_
books_by_security books_
Detailed Description
An implementation of jb::message_handler_concept to compute the inside.
Keep a collection of all the order books, and forward the right updates to them as it handles the different message types in ITCH-5.0.
Definition at line 30 of file compute_inside.hpp.
Class Documentation
struct jb::itch5::compute_inside::order_data
A convenient container for per-order data.
Most market data feeds resend the security identifier and side with each order update, but ITCH-5.0 does not. One needs to lookup that information based on the order id. This literal type is used to keep that information around.
Definition at line 150 of file compute_inside.hpp.
Class Members
buy_sell_indicator_t buy_sell_indicator
price4_t px
int qty
stock_t stock
Member Typedef Documentation
typedef std::unordered_map< stock_t, order_book, boost::hash<stock_t> > jb::itch5::compute_inside::books_by_security private
The collection of order books.
Definition at line 168 of file compute_inside.hpp.
typedef std::function<void(time_point, message_header const&, stock_t const&, half_quote const&, half_quote const&)> jb::itch5::compute_inside::callback_type
Callbacks.
Definition at line 42 of file compute_inside.hpp.
typedef std::unordered_map<std::uint64_t, order_data> jb::itch5::compute_inside::orders_by_id private
The list of live orders.
Definition at line 164 of file compute_inside.hpp.
typedef std::chrono::steady_clock::time_point jb::itch5::compute_inside::time_point
Define the clock used to measure processing delays.
Definition at line 37 of file compute_inside.hpp.
typedef std::tuple<bool, order_data, books_by_security::iterator> jb::itch5::compute_inside::update_result private
The result of a reduction is fairly complex ...
Definition at line 171 of file compute_inside.hpp.
Constructor & Destructor Documentation
jb::itch5::compute_inside::compute_inside (callback_type const & callback)
Initialize an empty handler.
Definition at line 4 of file compute_inside.cpp.
Member Function Documentation
jb::itch5::compute_inside::update_result jb::itch5::compute_inside::handle_add_order (time_point recv_ts, long msgcnt, std::size_t msgoffset, add_order_message const & msg) private
Refactor handling of add_order_message for both add_order and replace.
Definition at line 103 of file compute_inside.cpp.
References jb::itch5::add_order_message::buy_sell_indicator, jb::itch5::add_order_message::order_reference_number, jb::itch5::add_order_message::price, jb::itch5::add_order_message::shares, and jb::itch5::add_order_message::stock.
void jb::itch5::compute_inside::handle_message (time_point recv_ts, long msgcnt, std::size_t msgoffset, stock_directory_message const & msg)
Pre-populate the books based on the symbol directory.
ITCH-5.0 sends the list of expected securities to be traded on a given day as a sequence of messages. We use these messages to pre-populate the map of books and avoid hash map updates during the critical path.
Definition at line 10 of file compute_inside.cpp.
References JB_LOG, and jb::trace.
Referenced by BOOST_AUTO_TEST_CASE(), and handle_message().
void jb::itch5::compute_inside::handle_message (time_point recv_ts, long msgcnt, std::size_t msgoffset, add_order_message const & msg)
Handle a new order.
Definition at line 20 of file compute_inside.cpp.
References JB_LOG, and jb::trace.
void jb::itch5::compute_inside::handle_message (time_point recv_ts, long msgcnt, std::size_t msgoffset, add_order_mpid_message const & msg) inline
Handle a new order with MPID.
Definition at line 76 of file compute_inside.hpp.
References handle_message().
void jb::itch5::compute_inside::handle_message (time_point recv_ts, long msgcnt, std::size_t msgoffset, order_executed_message const & msg)
Handle an order execution.
Definition at line 35 of file compute_inside.cpp.
References JB_LOG, and jb::trace.
void jb::itch5::compute_inside::handle_message (time_point recv_ts, long msgcnt, std::size_t msgoffset, order_executed_price_message const & msg) inline
Handle an order execution.
Definition at line 95 of file compute_inside.hpp.
References handle_message().
void jb::itch5::compute_inside::handle_message (time_point recv_ts, long msgcnt, std::size_t msgoffset, order_cancel_message const & msg)
Handle a partial cancel.
Definition at line 44 of file compute_inside.cpp.
References JB_LOG, and jb::trace.
void jb::itch5::compute_inside::handle_message (time_point recv_ts, long msgcnt, std::size_t msgoffset, order_delete_message const & msg)
Handle a full cancel.
Definition at line 53 of file compute_inside.cpp.
References JB_LOG, and jb::trace.
void jb::itch5::compute_inside::handle_message (time_point recv_ts, long msgcnt, std::size_t msgoffset, order_replace_message const & msg)
Handle an order replace.
Definition at line 62 of file compute_inside.cpp.
References jb::itch5::compute_inside::order_data::buy_sell_indicator, jb::itch5::add_order_message::header, JB_LOG, jb::itch5::compute_inside::order_data::stock, and jb::trace.
template<typename message_type > void jb::itch5::compute_inside::handle_message (time_point recv_ts, long msgcnt, std::size_t msgoffset, message_type const & msg) inline
Ignore all other message types.
We are only interested in a handful of message types, anything else is captured by this template function and ignored.
Definition at line 132 of file compute_inside.hpp.
void jb::itch5::compute_inside::handle_reduce (time_point recv_ts, long msgcnt, std::size_t msgoffset, message_header const & header, std::uint64_t order_reference_number, std::uint32_t shares, bool all_shares) private
Handle both order executions and partial cancels.
Definition at line 138 of file compute_inside.cpp.
jb::itch5::compute_inside::update_result jb::itch5::compute_inside::handle_reduce_no_update (time_point recv_ts, long msgcnt, std::size_t msgoffset, message_header const & header, std::uint64_t order_reference_number, std::uint32_t shares, bool all_shares) private
Handle an order reduction, but do not update the callback.
Definition at line 157 of file compute_inside.cpp.
References jb::itch5::compute_inside::order_data::buy_sell_indicator, JB_ASSERT_THROW, JB_LOG, jb::itch5::compute_inside::order_data::px, and jb::warning.
void jb::itch5::compute_inside::handle_unknown (time_point recv_ts, unknown_message const & msg)
Log any unknown message types.
Definition at line 94 of file compute_inside.cpp.
References jb::itch5::unknown_message::buf(), jb::itch5::unknown_message::count(), jb::error, JB_LOG, and jb::itch5::unknown_message::offset().
Referenced by BOOST_AUTO_TEST_CASE().
std::size_t jb::itch5::compute_inside::live_order_count () const inline
An accessor to make testing easier.
Definition at line 158 of file compute_inside.hpp.
References orders_.
Referenced by BOOST_AUTO_TEST_CASE().
time_point jb::itch5::compute_inside::now () const inline
Return the current timestamp for delay measurements.
Definition at line 49 of file compute_inside.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
Member Data Documentation
books_by_security jb::itch5::compute_inside::books_ private
Definition at line 197 of file compute_inside.hpp.
callback_type jb::itch5::compute_inside::callback_ private
Store the callback ...
Definition at line 193 of file compute_inside.hpp.
orders_by_id jb::itch5::compute_inside::orders_ private
Definition at line 195 of file compute_inside.hpp.
Referenced by live_order_count().
The documentation for this class was generated from the following files:
jb/itch5/compute_inside.hpp
jb/itch5/compute_inside.cpp