JayBeams: jb/clfft/clfft_plan_ut.cpp File Reference
clfft_plan_ut.cpp File Reference
#include <jb/clfft/init.hpp>
#include <jb/clfft/plan.hpp>
#include <jb/opencl/device_selector.hpp>
#include <jb/testing/check_close_enough.hpp>
#include <jb/testing/create_square_timeseries.hpp>
#include <boost/test/unit_test.hpp>
#include <complex>
#include <vector>
Functions
BOOST_AUTO_TEST_CASE (clfft_plan_default)
BOOST_AUTO_TEST_CASE (clfft_plan_move)
BOOST_AUTO_TEST_CASE (clfft_plan_basic)
BOOST_AUTO_TEST_CASE (clfft_plan_error)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/4]
BOOST_AUTO_TEST_CASE (clfft_plan_default)
Test:
Verify that we can create and destroy default initialized plans.
Definition at line 14 of file clfft_plan_ut.cpp.
References jb::log::init().
BOOST_AUTO_TEST_CASE() [2/4]
BOOST_AUTO_TEST_CASE (clfft_plan_move)
Test:
Verify that we use move copy constructor and assignment on plans.
Definition at line 28 of file clfft_plan_ut.cpp.
References jb::clfft::create_forward_plan_1d(), jb::testing::create_square_timeseries(), jb::opencl::device_selector(), jb::clfft::plan< in_timeseries_type, out_timeseries_type >::enqueue(), jb::log::init(), and jb::testing::defaults::size.
BOOST_AUTO_TEST_CASE() [3/4]
BOOST_AUTO_TEST_CASE (clfft_plan_basic)
Test:
Verify that we can create clfft_plan objects and they work as expected.
Definition at line 73 of file clfft_plan_ut.cpp.
References jb::testing::check_collection_close_enough(), jb::clfft::create_forward_plan_1d(), jb::clfft::create_inverse_plan_1d(), jb::testing::create_square_timeseries(), jb::opencl::device_selector(), jb::log::init(), and jb::testing::defaults::size.
BOOST_AUTO_TEST_CASE() [4/4]
BOOST_AUTO_TEST_CASE (clfft_plan_error)
Test:
Verify that the plan detects errors and reports them.
Definition at line 114 of file clfft_plan_ut.cpp.
References jb::clfft::create_forward_plan_1d(), jb::opencl::device_selector(), jb::log::init(), and jb::testing::defaults::size.