JayBeams: tools/itch5eventdepth.cpp File Reference
itch5eventdepth.cpp File Reference
This program tries to answer the question:
#include <jb/itch5/compute_book.hpp>
#include <jb/itch5/price_levels.hpp>
#include <jb/itch5/process_iostream.hpp>
#include <jb/book_depth_statistics.hpp>
#include <jb/fileio.hpp>
#include <jb/log.hpp>
#include <chrono>
#include <iostream>
#include <stdexcept>
#include <unordered_map>
Macros
#define JB_ITCH5EVENTDEPTH_DEFAULT_per_symbol_max_book_depth 5000
Limit the amount of memory used on each per-symbol statistics.
Functions
int main (int argc, char *argv[])
Detailed Description
This program tries to answer the question:
How many changes happen at the top of book?
How many changes happen 2 levels down the book?
What about 10 levels?
It reports the percentiles of "for each event, record the depth of the change".
Definition in file itch5eventdepth.cpp.
Macro Definition Documentation
#define JB_ITCH5EVENTDEPTH_DEFAULT_per_symbol_max_book_depth 5000
Limit the amount of memory used on each per-symbol statistics.
Definition at line 138 of file itch5eventdepth.cpp.
Function Documentation
int main (int argc, char * argv[])
Definition at line 73 of file itch5eventdepth.cpp.
References jb::usage::exit_status(), jb::log::init(), jb::open_input_file(), jb::open_output_file(), jb::book_depth_statistics::print_csv_header(), jb::itch5::process_iostream(), and jb::itch5::compute_book::book_update::stock.