JayBeams: tools/itch5trades.cpp File Reference
itch5trades.cpp File Reference
This program reads a raw ITCH-5.0 file and prints out the trade messages into an ASCII (though potentially compressed) file.
#include <jb/itch5/process_iostream.hpp>
#include <jb/fileio.hpp>
#include <jb/log.hpp>
#include <stdexcept>
Functions
int main (int argc, char *argv[])
Detailed Description
This program reads a raw ITCH-5.0 file and prints out the trade messages into an ASCII (though potentially compressed) file.
Definition in file itch5trades.cpp.
Function Documentation
int main (int argc, char * argv[])
Definition at line 95 of file itch5trades.cpp.
References jb::itch5::char_list_field< V >::as_int(), jb::itch5::unknown_message::buf(), jb::itch5::trade_message::buy_sell_indicator, jb::itch5::unknown_message::count(), jb::usage::exit_status(), jb::itch5::trade_message::header, jb::log::init(), JB_LOG, jb::itch5::trade_message::match_number, jb::itch5::unknown_message::offset(), jb::open_input_file(), jb::open_output_file(), jb::itch5::trade_message::order_reference_number, jb::itch5::trade_message::price, jb::itch5::process_iostream(), jb::itch5::trade_message::shares, jb::itch5::trade_message::stock, jb::itch5::message_header::timestamp, and jb::itch5::timestamp::ts.