JayBeams: tools/itch5bookdepth.cpp File Reference
itch5bookdepth.cpp File Reference
Compute ITCH5 Depth of Book statistics.
#include <jb/itch5/compute_book.hpp>
#include <jb/itch5/process_iostream.hpp>
#include <jb/book_depth_statistics.hpp>
#include <jb/fileio.hpp>
#include <jb/log.hpp>
#include <chrono>
#include <iostream>
#include <stdexcept>
#include <unordered_map>
Macros
#define JB_ITCH5BOOKDEPTH_DEFAULT_per_symbol_max_book_depth 5000
Limit the amount of memory used on each per-symbol statistics.
Functions
int main (int argc, char *argv[])
Detailed Description
Compute ITCH5 Depth of Book statistics.
Generate statistics per symbol and aggregated. See: https://github.com/GFariasR/jaybeams/wiki/ITCH5-Depth-of-Book-StatisticsProject for design and implementation details.
Definition in file itch5bookdepth.cpp.
Macro Definition Documentation
#define JB_ITCH5BOOKDEPTH_DEFAULT_per_symbol_max_book_depth 5000
Limit the amount of memory used on each per-symbol statistics.
Definition at line 117 of file itch5bookdepth.cpp.
Function Documentation
int main (int argc, char * argv[])
Definition at line 53 of file itch5bookdepth.cpp.
References jb::usage::exit_status(), jb::log::init(), jb::open_input_file(), jb::open_output_file(), jb::book_depth_statistics::print_csv_header(), and jb::itch5::process_iostream().