JayBeams: jb/itch5/moldreplay.cpp File Reference
moldreplay.cpp File Reference
A program to replay raw ITCH-5.x files as MoldUDP packets.
#include <jb/ehs/acceptor.hpp>
#include <jb/itch5/mold_udp_pacer.hpp>
#include <jb/itch5/process_iostream_mlist.hpp>
#include <jb/as_hhmmss.hpp>
#include <jb/config_object.hpp>
#include <jb/fileio.hpp>
#include <jb/launch_thread.hpp>
#include <jb/log.hpp>
#include <beast/http.hpp>
#include <boost/asio/io_service.hpp>
#include <boost/asio/ip/address.hpp>
#include <boost/asio/ip/multicast.hpp>
#include <boost/asio/ip/tcp.hpp>
#include <boost/asio/ip/udp.hpp>
#include <chrono>
#include <iostream>
#include <stdexcept>
#include <thread>
Namespaces
defaults
Define defaults for program parameters.
Functions
int main (int argc, char *argv[])
Detailed Description
A program to replay raw ITCH-5.x files as MoldUDP packets.
This program replays a ITCH-5.x file via multicast, simulating the behavior of a market data feed.
Definition in file moldreplay.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 129 of file moldreplay.cpp.
References jb::itch5::unknown_message::count(), jb::usage::exit_status(), jb::log::init(), JB_ASSERT_THROW, jb::launch_thread(), jb::itch5::unknown_message::offset(), and jb::open_input_file().