JayBeams: tools/mold2inside.cpp File Reference
mold2inside.cpp File Reference
This program receives MoldUDP64 packets containing ITCH-5.0 messges and generates the inside quotes in an ASCII (though potentially compressed) file.
#include <jb/itch5/generate_inside.hpp>
#include <jb/itch5/mold_udp_channel.hpp>
#include <jb/itch5/process_iostream.hpp>
#include <jb/fileio.hpp>
#include <jb/log.hpp>
#include <stdexcept>
#include <unordered_map>
Macros
#define KNOWN_ITCH5_MESSAGES
Functions
int main (int argc, char *argv[])
Detailed Description
This program receives MoldUDP64 packets containing ITCH-5.0 messges and generates the inside quotes in an ASCII (though potentially compressed) file.
The program also generates statistics about the feed and the book build, using jb::offline_feed_statistics.
It reports the percentiles of "for each change in the inside, how long did it take to process the event, and what was the elapsed time since the last change to the inside".
Definition in file mold2inside.cpp.
Macro Definition Documentation
KNOWN_ITCH5_MESSAGES
#define KNOWN_ITCH5_MESSAGES
Value:
jb::itch5::add_order_message, jb::itch5::add_order_mpid_message,             \
      jb::itch5::broken_trade_message, jb::itch5::cross_trade_message,         \
      jb::itch5::ipo_quoting_period_update_message,                            \
      jb::itch5::market_participant_position_message,                          \
      jb::itch5::mwcb_breach_message, jb::itch5::mwcb_decline_level_message,   \
      jb::itch5::net_order_imbalance_indicator_message,                        \
      jb::itch5::order_cancel_message, jb::itch5::order_delete_message,        \
      jb::itch5::order_executed_message,                                       \
      jb::itch5::order_executed_price_message,                                 \
      jb::itch5::order_replace_message,                                        \
      jb::itch5::reg_sho_restriction_message,                                  \
      jb::itch5::stock_directory_message,                                      \
      jb::itch5::stock_trading_action_message,                                 \
      jb::itch5::system_event_message, jb::itch5::trade_message
Definition at line 48 of file mold2inside.cpp.
Referenced by main().
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 64 of file mold2inside.cpp.
References jb::config_object::desc(), jb::usage::exit_status(), jb::itch5::generate_inside(), jb::log::init(), KNOWN_ITCH5_MESSAGES, jb::open_output_file(), jb::offline_feed_statistics::print_csv_header(), and jb::offline_feed_statistics::config::reporting_interval_seconds.