JayBeams: jb::clfft Namespace Reference
jb::clfft Namespace Reference
Wrappers for the clFFT library.
Classes
class clfft_error
A run-time clFFT error.
class init
Wrap clfftPlanHandle objects in a class that can automatically destroy them.
class plan
Wrap clfftPlanHandle objects in a class that can automatically destroy them.
Functions
void check_error_code (cl_int err, char const *msg)
Check in an OpenCL error code is really an error and raise an exception if so.
template<typename invector , typename outvector >
plan< invector, outvector > create_forward_plan_1d (outvector const &out, invector const &in, boost::compute::context &ct, boost::compute::command_queue &q)
template<typename invector , typename outvector >
plan< invector, outvector > create_inverse_plan_1d (outvector const &out, invector const &in, boost::compute::context &ct, boost::compute::command_queue &q)
Detailed Description
Wrappers for the clFFT library.
Function Documentation
void jb::clfft::check_error_code (cl_int err, char const * msg) inline
Check in an OpenCL error code is really an error and raise an exception if so.
Definition at line 45 of file error.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), jb::clfft::plan< invector, outvector >::create_plan_1d_impl(), jb::clfft::plan< invector, outvector >::enqueue(), jb::clfft::init::init(), jb::clfft::init::~init(), and jb::clfft::plan< invector, outvector >::~plan().
template<typename invector , typename outvector > plan<invector, outvector> jb::clfft::create_forward_plan_1d (outvector const & out, invector const & in, boost::compute::context & ct, boost::compute::command_queue & q)
Definition at line 157 of file plan.hpp.
References jb::clfft::plan< invector, outvector >::create_forward_plan_1d().
Referenced by BOOST_AUTO_TEST_CASE(), and jb::fftw::plan< timeseries_type, frequency_timeseries_type >::execute().
template<typename invector , typename outvector > plan<invector, outvector> jb::clfft::create_inverse_plan_1d (outvector const & out, invector const & in, boost::compute::context & ct, boost::compute::command_queue & q)
Definition at line 164 of file plan.hpp.
References jb::clfft::plan< invector, outvector >::create_inverse_plan_1d().
Referenced by BOOST_AUTO_TEST_CASE().