JayBeams: jb::log Namespace Reference
jb::log Namespace Reference
Logging functions and objects for JayBeams.
Namespaces
defaults
Define the default values for logging configuration.
Classes
class config
Configuration object for the logging functions.
Functions
BOOST_LOG_ATTRIBUTE_KEYWORD (current_thread_id, "ThreadID", boost::log::attributes::current_thread_id::value_type) BOOST_LOG_ATTRIBUTE_KEYWORD(local_time
boost::log::attributes::local_clock::value_type bool filter_predicate (::boost::log::attribute_value_set const &attr)
void format_common (boost::log::record_view const &rec, boost::log::formatting_ostream &strm)
void format_console (boost::log::record_view const &rec, boost::log::formatting_ostream &strm)
void format_logfile (boost::log::record_view const &rec, boost::log::formatting_ostream &strm)
std::int64_t tid ()
void next_tid ()
void init (config const &cfg=config())
Initialize the logging functions using the configuration provided.
BOOST_LOG_INLINE_GLOBAL_LOGGER_DEFAULT (logger, boost::log::sources::severity_logger_mt< severity_level >) void next_tid()
Define the global logger for JayBeams.
Variables
TimeStamp
std::int64_t tid_
Detailed Description
Logging functions and objects for JayBeams.
Function Documentation
BOOST_LOG_ATTRIBUTE_KEYWORD()
jb::log::BOOST_LOG_ATTRIBUTE_KEYWORD (current_thread_id , "ThreadID" , boost::log::attributes::current_thread_id::value_type)
Referenced by jb::log::config::validate().
BOOST_LOG_INLINE_GLOBAL_LOGGER_DEFAULT()
jb::log::BOOST_LOG_INLINE_GLOBAL_LOGGER_DEFAULT (logger , boost::log::sources::severity_logger_mt< severity_level >)
Define the global logger for JayBeams.
filter_predicate()
boost::log::attributes::local_clock::value_type bool jb::log::filter_predicate (::boost::log::attribute_value_set const & attr)
Definition at line 143 of file log.cpp.
References jb::debug, and JB_ASSERT_THROW.
Referenced by init().
format_common()
void jb::log::format_common (boost::log::record_view const & rec, boost::log::formatting_ostream & strm)
Definition at line 155 of file log.cpp.
References jb::debug, and jb::severity_level_width().
Referenced by format_console(), and format_logfile().
format_console()
void jb::log::format_console (boost::log::record_view const & rec, boost::log::formatting_ostream & strm)
Definition at line 168 of file log.cpp.
References format_common().
Referenced by init().
format_logfile()
void jb::log::format_logfile (boost::log::record_view const & rec, boost::log::formatting_ostream & strm)
Definition at line 176 of file log.cpp.
References format_common().
Referenced by init().
init()
void jb::log::init (config const & cfg)
Initialize the logging functions using the configuration provided.
Definition at line 198 of file log.cpp.
References jb::log::config::enable_console_logging, jb::log::config::enable_file_logging, filter_predicate(), format_console(), format_logfile(), jb::log::config::logfile_archive_directory, jb::log::config::logfile_basename, jb::log::config::logfile_suffix, jb::itch5::defaults::max_size, jb::log::config::maximum_size_archived, jb::log::config::minimum_console_severity, jb::log::config::minimum_free_space, jb::log::config::minimum_severity, and tid().
Referenced by BOOST_AUTO_TEST_CASE(), main(), and run_inside().
next_tid()
void jb::log::next_tid ()
Definition at line 194 of file log.cpp.
References tid_.
Referenced by BOOST_AUTO_TEST_CASE().
tid()
std::int64_t jb::log::tid ()
Definition at line 190 of file log.cpp.
References tid_.
Referenced by init().
Variable Documentation
tid_
std::int64_t jb::log::tid_
Definition at line 188 of file log.cpp.
Referenced by next_tid(), and tid().
TimeStamp
jb::log::TimeStamp
Definition at line 141 of file log.cpp.