JayBeams: jb Namespace Reference
jb Namespace Reference
The top-level namespace for the JayBeams library.
Namespaces
defaults
Default values for configuration parameters.
examples
Contains types and functions useful in the examples.
fftw
Wrappers for the FFTW3 library.
itch5
Contains classes and functions to parse NASDAQ ITCH-5.0 messages, more information about ITCH-5.0 can be found at: http://www.nasdaqtrader.com/content/technicalsupport/specifications/dataproducts/NQTVITCHSpecification.pdf.
log
Logging functions and objects for JayBeams.
testing
Helper functions and classes to simplify unit tests.
yaml
Classes
struct as_hhmmssu
Helper class to print time durations in a HHMMSS.UUUUUU format.
struct as_hhmmss
Helper class to print time durations s in HHMMSS format.
struct as_hh_mm_ss_u
Helper class to print time durations in HH:MM:SS.UUUUUU format.
struct extract_value_type
Generic function to extract the floating point type of std::complex.
struct extract_value_type< std::complex< T > >
Partial specialization of jb::extract_value_type for std::complex.
class config_attribute
Helper class to easily define configuration attributes.
struct default_getenv
Define the functor to read configuration variables from the environment.
struct default_validator
Define the functor to validate if paths are readable.
class config_files_locations_base
Define the configuration file search algorithm for JayBeams.
class config_files_locations
Compute the directories where a configuration file can be found.
class config_object
Base class for all configuration objects.
struct config_recurse
Recursively apply functions to config_object, attributes, and sequences of config objects.
class event_rate_estimator
Estimate event rates over a trailing measurement period.
class event_rate_histogram
Keep a histogram of observed event rates.
class explicit_cuts_binning
A histogram binning_strategy for integer numbers with user defined cuts.
class histogram
A histogram class with controllable binning and range strategy.
struct histogram_summary
A simple class to capture summary information about a histogram.
class integer_range_binning
A histogram binning_strategy for integer numbers in a known range.
class offline_feed_statistics
Keep statistics about a feed and its offline processor.
struct stn_traits
Traits to convert strings to numbers (e.g.
class usage
A simple class to communicate the result of parsing the options.
class binning_strategy_concept
The interface that must be met by the binning_strategy in jb::histogram.
Typedefs
typedef std::map< std::string,
YAML::Node > class_overrides
Store the overrides for each class.
Enumerations
enum severity_level {
severity_level::trace, severity_level::debug, severity_level::info, severity_level::notice,
severity_level::warning, severity_level::error, severity_level::critical, severity_level::alert,
severity_level::fatal
}
Severity levels for JayBeams, based on syslog.
Functions
std::ostream & operator<< (std::ostream &os, as_hhmmssu const &x)
Format as_hhmmssu into an iostream.
std::ostream & operator<< (std::ostream &os, as_hhmmss const &x)
Format as_hhmmss into an iostream.
std::ostream & operator<< (std::ostream &os, as_hh_mm_ss_u const &x)
Format as_hh_mm_ss_u into an iostream.
void raise_assertion_failure (char const *filename, int lineno, char const *predicate)
Raise std::exception to indicate an assertion failure.
char const * sysconfdir ()
Return the system configuration directory.
char const * bindir ()
Return the binary installation directory directory.
std::ostream & operator<< (std::ostream &os, config_object const &x)
void open_output_file (boost::iostreams::filtering_ostream &out, std::string const &filename)
Open a file for writing.
void open_input_file (boost::iostreams::filtering_istream &in, std::string const &filename)
Open a file for reading.
bool is_gz (std::string const &filename)
Return true if the filename ends in .gz.
template<typename sample_type >
sample_type histogram_binning_linear_interpolation (sample_type x_a, sample_type x_b, double y_a, double s, double q)
Convenience function to implement the binning_strategy_concept.
std::ostream & operator<< (std::ostream &os, histogram_summary const &x)
constexpr bool severity_static_predicate (jb::severity_level lvl)
Statically check if the severity level should even be compiled in.
std::ostream & operator<< (std::ostream &os, severity_level const &x)
Streaming for severity levels.
std::istream & operator>> (std::istream &is, severity_level &x)
void parse (severity_level &lhs, std::string const &rhs)
Parse a severity level.
char const * get_name (severity_level const &rhs)
Get the name of a security level.
int severity_level_width ()
Return the recommended with for printing security levels.
STN_TRAITS (int, std::stoi)
STN_TRAITS (unsigned long long, std::stoull)
STN_TRAITS (long long, std::stoll)
STN_TRAITS (unsigned long, std::stoul)
STN_TRAITS (long, std::stol)
STN_TRAITS (float, std::stof)
STN_TRAITS (double, std::stod)
template<typename T >
bool strtonum (std::string const &s, T &r)
Generic string to number conversion with validation.
Detailed Description
The top-level namespace for the JayBeams library.
Class Documentation
struct jb::extract_value_type
template<typename T>
struct jb::extract_value_type< T >
Generic function to extract the floating point type of std::complex.
Some of the algorithms and data structures in JayBeams need to work for both std::complex<> and for primitive floating point values such as 'float'. These functions sometimes need a generic way to extract the 'T' parameter in a std::complex<T>. This function can be used to perform such conversions, for example:
template<typename sample_t> class Foo {
  typedef typename jb::extra_value_type<sample_t>::precision prec;
  prec epsilon = std::numeric_limits<prec>::epsilon();
};
Such code would work whether sample_t is a std::complex<T> or a primitive floating point value.
Definition at line 28 of file complex_traits.hpp.
Class Members
typedef T precision
struct jb::extract_value_type< std::complex< T > >
template<typename T>
struct jb::extract_value_type< std::complex< T > >
Partial specialization of jb::extract_value_type for std::complex.
Definition at line 34 of file complex_traits.hpp.
Class Members
typedef T precision
struct jb::histogram_summary
A simple class to capture summary information about a histogram.
Definition at line 9 of file histogram_summary.hpp.
Class Members
double max
double min
size_t nsamples
double p25
double p50
double p75
double p90
double p99
struct jb::stn_traits
template<typename T>
struct jb::stn_traits< T >
Traits to convert strings to numbers (e.g.
integers, floats, etc).
For most types this refactors repetitive code, but also allows specialization for specific types.
Definition at line 15 of file strtonum.hpp.
Typedef Documentation
typedef std::map<std::string,YAML::Node> jb::class_overrides
Store the overrides for each class.
Jaybeams configuration objects can be overriden "by-class", meaning, all configs of the same class receive the same overrides. This type is used to (temporarily) store the by-class overrides in a given context.
Definition at line 17 of file merge_yaml.hpp.
Enumeration Type Documentation
enum jb::severity_level strong
Severity levels for JayBeams, based on syslog.
Enumerator
trace
debug
info
notice
warning
error
critical
alert
fatal
Definition at line 10 of file severity_level.hpp.
Function Documentation
char const * jb::bindir ()
Return the binary installation directory directory.
Typically this is something like /usr/bin or /usr/local/bin but it can change depending on how JayBeams was configured and the target platform.
Definition at line 81 of file config_files_location.cpp.
References JB_DEFAULT_BINDIR.
Referenced by BOOST_AUTO_TEST_CASE(), and jb::config_files_locations_base::config_files_locations_base().
char const * jb::get_name (severity_level const & rhs)
Get the name of a security level.
Definition at line 66 of file severity_level.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and YAML::convert< jb::severity_level >::encode().
template<typename sample_type > sample_type jb::histogram_binning_linear_interpolation (sample_type x_a, sample_type x_b, double y_a, double s, double q) inline
Convenience function to implement the binning_strategy_concept.
The histogram class requires the binning strategy to solve the follow equation for \(x\):
\[ {{(x - x_a)} \over {(y - y_a)}} = {{(x_b - x_a)} \over {s}} \]
this is used in the computation of percentiles to better approximate the percentile value between different cuts. Some binning strategies might provide a non-linear interpolation, but in practice this (linear) solution is used in most cases.
Definition at line 24 of file histogram_binning_linear_interpolation.hpp.
Referenced by jb::integer_range_binning< std::int64_t >::interpolate(), and jb::explicit_cuts_binning< sample_type_t >::interpolate().
bool jb::is_gz (std::string const & filename)
Return true if the filename ends in .gz.
Definition at line 3 of file filetype.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), open_input_file(), and open_output_file().
void jb::open_input_file (boost::iostreams::filtering_istream & in, std::string const & filename)
Open a file for reading.
Definition at line 28 of file fileio.cpp.
References is_gz().
Referenced by check_read_write(), and main().
void jb::open_output_file (boost::iostreams::filtering_ostream & out, std::string const & filename)
Open a file for writing.
Definition at line 11 of file fileio.cpp.
References is_gz().
Referenced by BOOST_AUTO_TEST_CASE(), check_read_write(), and main().
std::ostream & jb::operator<< (std::ostream & os, histogram_summary const & x)
Definition at line 5 of file histogram_summary.cpp.
References jb::histogram_summary::max, jb::histogram_summary::min, jb::histogram_summary::nsamples, jb::histogram_summary::p25, jb::histogram_summary::p50, jb::histogram_summary::p75, jb::histogram_summary::p90, and jb::histogram_summary::p99.
std::ostream & jb::operator<< (std::ostream & os, severity_level const & x)
Streaming for severity levels.
Definition at line 35 of file severity_level.cpp.
std::ostream & jb::operator<< (std::ostream & os, jb::as_hhmmssu const & x)
Format as_hhmmssu into an iostream.
Definition at line 6 of file as_hhmmss.cpp.
References jb::as_hhmmssu::t.
std::ostream & jb::operator<< (std::ostream & os, jb::as_hhmmss const & x)
Format as_hhmmss into an iostream.
Definition at line 12 of file as_hhmmss.cpp.
References jb::as_hhmmss::t.
std::ostream & jb::operator<< (std::ostream & os, jb::as_hh_mm_ss_u const & x)
Format as_hh_mm_ss_u into an iostream.
Definition at line 24 of file as_hhmmss.cpp.
References jb::as_hh_mm_ss_u::t.
std::ostream& jb::operator<< (std::ostream & os, config_object const & x) inline
Definition at line 314 of file config_object.hpp.
References jb::config_object::to_stream().
std::istream & jb::operator>> (std::istream & is, severity_level & x)
Definition at line 45 of file severity_level.cpp.
References parse().
void jb::parse (severity_level & lhs, std::string const & rhs)
Parse a severity level.
Definition at line 52 of file severity_level.cpp.
Referenced by YAML::convert< jb::severity_level >::decode(), and operator>>().
void jb::raise_assertion_failure (char const * filename, int lineno, char const * predicate)
Raise std::exception to indicate an assertion failure.
Definition at line 6 of file assert_throw.cpp.
int jb::severity_level_width ()
Return the recommended with for printing security levels.
Definition at line 77 of file severity_level.cpp.
Referenced by jb::log::format_common().
constexpr bool jb::severity_static_predicate (jb::severity_level lvl)
Statically check if the severity level should even be compiled in.
Definition at line 19 of file log.hpp.
References JB_MIN_LOG_LEVEL.
jb::STN_TRAITS (int , std::stoi)
jb::STN_TRAITS (unsigned long long, std::stoull)
jb::STN_TRAITS (long long, std::stoll)
jb::STN_TRAITS (unsigned long, std::stoul)
jb::STN_TRAITS (long , std::stol)
jb::STN_TRAITS (float , std::stof)
jb::STN_TRAITS (double , std::stod)
template<typename T > bool jb::strtonum (std::string const & s, T & r)
Generic string to number conversion with validation.
Definition at line 38 of file strtonum.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), and thread_config::native_priority().
char const * jb::sysconfdir ()
Return the system configuration directory.
Typically this is something like /etc or /usr/local/etc but it can change depending on how JayBeams was configured and the target platform.
Definition at line 74 of file config_files_location.cpp.
References JB_DEFAULT_SYSCONFDIR.
Referenced by BOOST_AUTO_TEST_CASE(), and jb::config_files_locations_base::config_files_locations_base().