JayBeams: jb::testing::detail Namespace Reference
jb::testing::detail Namespace Reference
Functions
template<typename Fixture , typename... Args>
void call_iteration_setup (Fixture &&, Args &&...)
A helper to call Fixture::iteration_setup() in the microbenchmarks.
template<typename Fixture , typename = decltype(std::declval<Fixture>().iteration_setup())>
void call_iteration_setup (Fixture &&fixture)
A helper to call Fixture::iteration_setup() in the microbenchmarks.
template<typename Fixture , typename... Args>
void call_iteration_teardown (Fixture &&, Args &&...)
A helper to call Fixture::iteration_teardown() in the microbenchmarks.
template<typename Fixture , typename = decltype(std::declval<Fixture>().iteration_teardown())>
void call_iteration_teardown (Fixture &&fixture)
A helper to call Fixture::iteration_teardown() in the microbenchmarks.
int report_exception_at_exit ()
Function Documentation
call_iteration_setup() [1/2]
template<typename Fixture , typename... Args> void jb::testing::detail::call_iteration_setup (Fixture && , Args && ...)
A helper to call Fixture::iteration_setup() in the microbenchmarks.
This is the no-op for fixtures that do not provide a iteration_setup() member function.
Template Parameters
Fixture the type of the Fixture
Args unused, just a way for SFINAE to fallback on something.
Definition at line 24 of file microbenchmark.hpp.
Referenced by jb::testing::microbenchmark< Fixture >::run_base(), and jb::testing::microbenchmark< Fixture >::run_iteration().
call_iteration_setup() [2/2]
template<typename Fixture , typename = decltype(std::declval<Fixture>().iteration_setup())> void jb::testing::detail::call_iteration_setup (Fixture && fixture)
A helper to call Fixture::iteration_setup() in the microbenchmarks.
This is the version for fixtures that do provide a iteration_setup() member function.
Template Parameters
Fixture the type of the Fixture
Definition at line 38 of file microbenchmark.hpp.
call_iteration_teardown() [1/2]
template<typename Fixture , typename... Args> void jb::testing::detail::call_iteration_teardown (Fixture && , Args && ...)
A helper to call Fixture::iteration_teardown() in the microbenchmarks.
This is the no-op for fixtures that do not provide a iteration_teardown() member function.
Template Parameters
Fixture the type of the Fixture
Args unused, just a way for SFINAE to fallback on something.
Definition at line 52 of file microbenchmark.hpp.
Referenced by jb::testing::microbenchmark< Fixture >::run_base(), and jb::testing::microbenchmark< Fixture >::run_iteration().
call_iteration_teardown() [2/2]
template<typename Fixture , typename = decltype(std::declval<Fixture>().iteration_teardown())> void jb::testing::detail::call_iteration_teardown (Fixture && fixture)
A helper to call Fixture::iteration_teardown() in the microbenchmarks.
This is the version for fixtures that do provide a iteration_teardown() member function.
Template Parameters
Fixture the type of the Fixture
Definition at line 66 of file microbenchmark.hpp.
report_exception_at_exit()
int jb::testing::detail::report_exception_at_exit ()
Definition at line 39 of file microbenchmark_group_main.cpp.
References jb::usage::exit_status().
Referenced by jb::testing::microbenchmark_group_main().