JayBeams: jb::fftw::detail Namespace Reference
jb::fftw::detail Namespace Reference
Classes
struct container_traits
Define traits for container-like types.
struct container_traits< boost::multi_array< T, K, A > >
Define traits for boost::multi_array<> containers.
Functions
void check_plan_inputs (std::size_t in_elements, std::size_t on_elements, std::size_t in_nsamples, std::size_t on_nsamples, char const *function_name)
Helper function to check the inputs to a create_*_plan_*()
template<typename T , std::size_t K, typename A >
std::size_t element_count (boost::multi_array< T, K, A > const &a)
Count the number of elements in boost::multi_array<>
template<typename T , std::size_t K, typename A >
std::size_t nsamples (boost::multi_array< T, K, A > const &a)
Count the number of samples in a boost::multi_array<>
template<typename T , typename A >
std::size_t element_count (std::vector< T, A > const &a)
Count the number of elements in a std::vector<>
template<typename T , typename A >
std::size_t nsamples (std::vector< T, A > const &a)
Count the number of samples in a std::vector<>
Class Documentation
struct jb::fftw::detail::container_traits
template<typename T>
struct jb::fftw::detail::container_traits< T >
Define traits for container-like types.
Definition at line 20 of file plan.hpp.
Class Members
typedef value_type element_type Define the type of the elements in the container.
struct jb::fftw::detail::container_traits< boost::multi_array< T, K, A > >
template<typename T, std::size_t K, typename A>
struct jb::fftw::detail::container_traits< boost::multi_array< T, K, A > >
Define traits for boost::multi_array<> containers.
Definition at line 29 of file plan.hpp.
Class Members
typedef multi_array< T, K, A >
::element element_type Define the type of the elements in the array.
Function Documentation
void jb::fftw::detail::check_plan_inputs (std::size_t in_elements, std::size_t on_elements, std::size_t in_nsamples, std::size_t on_nsamples, char const * function_name)
Helper function to check the inputs to a create_*_plan_*()
Parameters
in_elements the number of elements in the input vector or array
on_elements the number of elements in the output vector or array
in_nsamples the number of samples per-timeseries in the input array
on_nsamples the number of samples per timeseries in the output array
function_name the name of the function to include in the exception message if a problem is detected
Exceptions
std::invalid_argument if the sizes do not match, with a descriptive message.
Definition at line 10 of file plan.cpp.
Referenced by jb::fftw::create_backward_plan(), jb::fftw::create_forward_plan(), and jb::fftw::plan< timeseries_type, frequency_timeseries_type >::execute().
template<typename T , std::size_t K, typename A > std::size_t jb::fftw::detail::element_count (boost::multi_array< T, K, A > const & a)
Count the number of elements in boost::multi_array<>
Definition at line 52 of file plan.hpp.
Referenced by jb::fftw::create_backward_plan(), jb::fftw::create_forward_plan(), and jb::fftw::plan< timeseries_type, frequency_timeseries_type >::execute().
template<typename T , typename A > std::size_t jb::fftw::detail::element_count (std::vector< T, A > const & a)
Count the number of elements in a std::vector<>
Definition at line 64 of file plan.hpp.
template<typename T , std::size_t K, typename A > std::size_t jb::fftw::detail::nsamples (boost::multi_array< T, K, A > const & a)
Count the number of samples in a boost::multi_array<>
Definition at line 58 of file plan.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), jb::fftw::create_backward_plan(), jb::fftw::create_forward_plan(), jb::testing::create_square_timeseries(), and jb::fftw::plan< timeseries_type, frequency_timeseries_type >::execute().
template<typename T , typename A > std::size_t jb::fftw::detail::nsamples (std::vector< T, A > const & a)
Count the number of samples in a std::vector<>
Definition at line 70 of file plan.hpp.