JayBeams: jb::opencl Namespace Reference
jb::opencl Namespace Reference
Wrappers for the OpenCL library.
Namespaces
defaults
detail
Classes
class config
Configure the OpenCL device / context options.
Functions
boost::compute::kernel build_simple_kernel (boost::compute::context context, boost::compute::device device, char const *code, char const *kernel_name)
Build a simple program (one where everything is in a single string) and get a kernel from it.
boost::compute::kernel build_simple_kernel (boost::compute::context context, boost::compute::device device, std::istream &code, char const *kernel_name)
Build a simple program from an iostream and get a kernel from the result.
boost::compute::program build_simple_program (boost::compute::context context, boost::compute::device device, char const *code)
Convenience function to build a simple program and return it.
boost::compute::program build_simple_program (boost::compute::context context, boost::compute::device device, std::istream &code)
Convenience function to build a simple program and return it.
template<class DeviceIterator , class HostIterator >
boost::compute::future< HostIterator > copy_to_host_async (DeviceIterator first, DeviceIterator last, HostIterator result, boost::compute::command_queue &queue, boost::compute::wait_list const &wait=boost::compute::wait_list())
Copy a device buffer to the host asynchronously.
boost::compute::device device_selector (config const &cfg)
Select an OpenCL device matching the current configuration.
boost::compute::device device_selector ()
Return the default OpenCL device.
Detailed Description
Wrappers for the OpenCL library.
Function Documentation
build_simple_kernel() [1/2]
boost::compute::kernel jb::opencl::build_simple_kernel (boost::compute::context context, boost::compute::device device, char const * code, char const * kernel_name)
Build a simple program (one where everything is in a single string) and get a kernel from it.
Most of our kernels are relatively simple, so this routine is very convenient.
Definition at line 6 of file build_simple_kernel.cpp.
References build_simple_program().
Referenced by BOOST_AUTO_TEST_CASE().
build_simple_kernel() [2/2]
boost::compute::kernel jb::opencl::build_simple_kernel (boost::compute::context context, boost::compute::device device, std::istream & code, char const * kernel_name)
Build a simple program from an iostream and get a kernel from the result.
Definition at line 13 of file build_simple_kernel.cpp.
References build_simple_program().
build_simple_program() [1/2]
boost::compute::program jb::opencl::build_simple_program (boost::compute::context context, boost::compute::device device, char const * code)
Convenience function to build a simple program and return it.
Build a problem that consists of a single source string, targeted to a single device.
Definition at line 20 of file build_simple_kernel.cpp.
References jb::error, and JB_LOG.
Referenced by BOOST_AUTO_TEST_CASE(), build_simple_kernel(), and build_simple_program().
build_simple_program() [2/2]
boost::compute::program jb::opencl::build_simple_program (boost::compute::context context, boost::compute::device device, std::istream & code)
Convenience function to build a simple program and return it.
Definition at line 38 of file build_simple_kernel.cpp.
References build_simple_program().
copy_to_host_async()
template<class DeviceIterator , class HostIterator > boost::compute::future<HostIterator> jb::opencl::copy_to_host_async (DeviceIterator first, DeviceIterator last, HostIterator result, boost::compute::command_queue & queue, boost::compute::wait_list const & wait = boost::compute::wait_list()) inline
Copy a device buffer to the host asynchronously.
Copies the range [first, last) from the device to the host, storing the results at result. The copy is started after all the events in wait have completed. The function returns a future object so you can wait for the copy to complete, and chain other operations.
Template Parameters
DeviceIterator the iterator type for the container on the device
HostIterator the iterator type for the container on the host
Parameters
first the beginning of the range to copy
last the end of the range to copy
result the beginning of the range to store the copy
queue command queue to perform the operation
wait a list of events (potentially empty) to wait for before starting the copy
Returns
A Future, once fulfilled it points to the end of the result range.
Definition at line 31 of file copy_to_host_async.hpp.
device_selector() [1/2]
boost::compute::device jb::opencl::device_selector (config const & cfg)
Select an OpenCL device matching the current configuration.
Definition at line 6 of file device_selector.cpp.
References jb::opencl::detail::best_device(), and jb::opencl::config::device_name.
Referenced by BOOST_AUTO_TEST_CASE(), jb::tde::reduce_sum< T >::combine_body(), device_selector(), and main().
device_selector() [2/2]
boost::compute::device jb::opencl::device_selector ()
Return the default OpenCL device.
Definition at line 25 of file device_selector.cpp.
References device_selector().