JayBeams: YAML::convert< jb::cpu_set > Struct Template Reference
YAML::convert< jb::cpu_set > Struct Template Reference
Specialize YAML conversions for jb::cpu_set.
#include <convert_cpu_set.hpp>
Static Public Member Functions
static bool decode (YAML::Node node, jb::cpu_set &rhs)
static YAML::Node encode (jb::cpu_set const &x)
Detailed Description
template<>
struct YAML::convert< jb::cpu_set >
Specialize YAML conversions for jb::cpu_set.
Arguably this might belong in the header defining jb::cpu_set, but this is specific to using a cpu_set in configuration objects.
Definition at line 16 of file convert_cpu_set.hpp.
Member Function Documentation
decode()
static bool YAML::convert< jb::cpu_set >::decode (YAML::Node node, jb::cpu_set & rhs) inline static
Definition at line 17 of file convert_cpu_set.hpp.
References jb::cpu_set::parse().
Referenced by BOOST_AUTO_TEST_CASE().
encode()
static YAML::Node YAML::convert< jb::cpu_set >::encode (jb::cpu_set const & x) inline static
Definition at line 22 of file convert_cpu_set.hpp.
References jb::cpu_set::as_list_format().
Referenced by BOOST_AUTO_TEST_CASE().
The documentation for this struct was generated from the following file:
jb/convert_cpu_set.hpp