JayBeams: jb::itch5::add_order_mpid_message Struct Reference
jb::itch5::add_order_mpid_message Struct Reference
Represent an 'Add Order with MPID' message in the ITCH-5.0 protocol.
#include <add_order_mpid_message.hpp>
Public Member Functions
add_order_mpid_message (add_order_message const &base, mpid_t const &a)
add_order_mpid_message ()=default
add_order_mpid_message (add_order_mpid_message const &)=default
add_order_mpid_message (add_order_mpid_message &&)=default
add_order_mpid_message & operator= (add_order_mpid_message const &)=default
add_order_mpid_message & operator= (add_order_mpid_message &&)=default
add_order_mpid_message & operator= (add_order_message const &rhs)
add_order_mpid_message & operator= (add_order_message &&rhs)
Public Attributes
mpid_t attribution
Public Attributes inherited from jb::itch5::add_order_message
message_header header
std::uint64_t order_reference_number
buy_sell_indicator_t buy_sell_indicator
int shares
stock_t stock
price4_t price
Static Public Attributes
static constexpr int message_type = u'F'
Static Public Attributes inherited from jb::itch5::add_order_message
static constexpr int message_type = u'A'
Detailed Description
Represent an 'Add Order with MPID' message in the ITCH-5.0 protocol.
Definition at line 13 of file add_order_mpid_message.hpp.
Constructor & Destructor Documentation
jb::itch5::add_order_mpid_message::add_order_mpid_message (add_order_message const & base, mpid_t const & a) inline
Definition at line 18 of file add_order_mpid_message.hpp.
References add_order_mpid_message(), and operator=().
jb::itch5::add_order_mpid_message::add_order_mpid_message () default
Referenced by add_order_mpid_message().
jb::itch5::add_order_mpid_message::add_order_mpid_message (add_order_mpid_message const &) default
jb::itch5::add_order_mpid_message::add_order_mpid_message (add_order_mpid_message &&) default
Member Function Documentation
add_order_mpid_message& jb::itch5::add_order_mpid_message::operator= (add_order_mpid_message const &) default
Referenced by add_order_mpid_message().
add_order_mpid_message& jb::itch5::add_order_mpid_message::operator= (add_order_mpid_message &&) default
add_order_mpid_message& jb::itch5::add_order_mpid_message::operator= (add_order_message const & rhs) inline
Definition at line 29 of file add_order_mpid_message.hpp.
add_order_mpid_message& jb::itch5::add_order_mpid_message::operator= (add_order_message && rhs) inline
Definition at line 33 of file add_order_mpid_message.hpp.
Member Data Documentation
mpid_t jb::itch5::add_order_mpid_message::attribution
Definition at line 16 of file add_order_mpid_message.hpp.
Referenced by jb::itch5::operator<<(), and jb::itch5::decoder< V, add_order_mpid_message >::r().
constexpr int jb::itch5::add_order_mpid_message::message_type = u'F' static
Definition at line 14 of file add_order_mpid_message.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), jb::itch5::testing::test_compute_book_order_cancel_message(), jb::itch5::testing::test_compute_book_order_executed_message(), and jb::itch5::testing::test_compute_book_order_replace_message().
The documentation for this struct was generated from the following files:
jb/itch5/add_order_mpid_message.hpp
jb/itch5/add_order_mpid_message.cpp