JayBeams: jb::itch5::mold_udp_channel_tester Struct Reference
jb::itch5::mold_udp_channel_tester Struct Reference
Break encapsulation in jb::itch5::mold_udp_channel for testing purposes.
Static Public Member Functions
static void call_with_empty_packet (mold_udp_channel &tested)
static void call_with_error_code (mold_udp_channel &tested)
Detailed Description
Break encapsulation in jb::itch5::mold_udp_channel for testing purposes.
Definition at line 81 of file ut_mold_udp_channel.cpp.
Member Function Documentation
call_with_empty_packet()
static void jb::itch5::mold_udp_channel_tester::call_with_empty_packet (mold_udp_channel & tested) inline static
Definition at line 82 of file ut_mold_udp_channel.cpp.
References jb::itch5::mold_udp_channel::handle_received().
Referenced by BOOST_AUTO_TEST_CASE().
call_with_error_code()
static void jb::itch5::mold_udp_channel_tester::call_with_error_code (mold_udp_channel & tested) inline static
Definition at line 85 of file ut_mold_udp_channel.cpp.
References jb::itch5::mold_udp_channel::handle_received().
Referenced by BOOST_AUTO_TEST_CASE().
The documentation for this struct was generated from the following file:
jb/itch5/ut_mold_udp_channel.cpp