JayBeams: jb::itch5::order_executed_price_message Struct Reference
jb::itch5::order_executed_price_message Struct Reference
Represent an 'Order Executed with Price' message in the ITCH-5.0 protocol.
#include <order_executed_price_message.hpp>
Public Member Functions
order_executed_price_message (order_executed_message const &base, printable_t const &p, price4_t const &px)
order_executed_price_message ()=default
order_executed_price_message (order_executed_price_message const &)=default
order_executed_price_message (order_executed_price_message &&)=default
order_executed_price_message & operator= (order_executed_price_message const &)=default
order_executed_price_message & operator= (order_executed_price_message &&)=default
order_executed_price_message & operator= (order_executed_message const &rhs)
order_executed_price_message & operator= (order_executed_message &&rhs)
Public Attributes
printable_t printable
price4_t execution_price
Public Attributes inherited from jb::itch5::order_executed_message
message_header header
std::uint64_t order_reference_number
std::uint32_t executed_shares
std::uint64_t match_number
Static Public Attributes
static constexpr int message_type = u'C'
Static Public Attributes inherited from jb::itch5::order_executed_message
static constexpr int message_type = u'E'
Detailed Description
Represent an 'Order Executed with Price' message in the ITCH-5.0 protocol.
Definition at line 22 of file order_executed_price_message.hpp.
Constructor & Destructor Documentation
order_executed_price_message() [1/4]
jb::itch5::order_executed_price_message::order_executed_price_message (order_executed_message const & base, printable_t const & p, price4_t const & px) inline
Definition at line 28 of file order_executed_price_message.hpp.
References operator=(), and order_executed_price_message().
order_executed_price_message() [2/4]
jb::itch5::order_executed_price_message::order_executed_price_message () default
Referenced by order_executed_price_message().
order_executed_price_message() [3/4]
jb::itch5::order_executed_price_message::order_executed_price_message (order_executed_price_message const &) default
order_executed_price_message() [4/4]
jb::itch5::order_executed_price_message::order_executed_price_message (order_executed_price_message &&) default
Member Function Documentation
operator=() [1/4]
order_executed_price_message& jb::itch5::order_executed_price_message::operator= (order_executed_price_message const &) default
Referenced by order_executed_price_message().
operator=() [2/4]
order_executed_price_message& jb::itch5::order_executed_price_message::operator= (order_executed_price_message &&) default
operator=() [3/4]
order_executed_price_message& jb::itch5::order_executed_price_message::operator= (order_executed_message const & rhs) inline
Definition at line 44 of file order_executed_price_message.hpp.
operator=() [4/4]
order_executed_price_message& jb::itch5::order_executed_price_message::operator= (order_executed_message && rhs) inline
Definition at line 48 of file order_executed_price_message.hpp.
Member Data Documentation
execution_price
price4_t jb::itch5::order_executed_price_message::execution_price
Definition at line 26 of file order_executed_price_message.hpp.
Referenced by jb::itch5::operator<<(), and jb::itch5::decoder< V, order_executed_price_message >::r().
message_type
constexpr int jb::itch5::order_executed_price_message::message_type = u'C' static
Definition at line 23 of file order_executed_price_message.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), and jb::itch5::testing::test_compute_book_order_executed_message().
printable
printable_t jb::itch5::order_executed_price_message::printable
Definition at line 25 of file order_executed_price_message.hpp.
Referenced by jb::itch5::operator<<(), and jb::itch5::decoder< V, order_executed_price_message >::r().
The documentation for this struct was generated from the following files:
jb/itch5/order_executed_price_message.hpp
jb/itch5/order_executed_price_message.cpp