JayBeams: jb/ut_offline_feed_statistics.cpp File Reference
ut_offline_feed_statistics.cpp File Reference
#include <jb/offline_feed_statistics.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (offline_feed_statististics_simple)
BOOST_AUTO_TEST_CASE (offline_feed_statististics_print_csv)
BOOST_AUTO_TEST_CASE (offline_feed_statististics_config_simple)
BOOST_AUTO_TEST_CASE (offline_feed_statististics_coverage)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/4]
BOOST_AUTO_TEST_CASE (offline_feed_statististics_simple)
Test:
Verify that jb::offline_feed_statistics works as expected.
Definition at line 8 of file ut_offline_feed_statistics.cpp.
References jb::offline_feed_statistics::sample().
BOOST_AUTO_TEST_CASE() [2/4]
BOOST_AUTO_TEST_CASE (offline_feed_statististics_print_csv)
Test:
Test jb::offline_feed_statistics csv output.
Definition at line 31 of file ut_offline_feed_statistics.cpp.
References jb::offline_feed_statistics::print_csv(), jb::offline_feed_statistics::print_csv_header(), and jb::offline_feed_statistics::sample().
BOOST_AUTO_TEST_CASE() [3/4]
BOOST_AUTO_TEST_CASE (offline_feed_statististics_config_simple)
Test:
Verify that jb::offline_feed_statistics::config works as expected.
Definition at line 66 of file ut_offline_feed_statistics.cpp.
References jb::defaults::max_interarrival_time_nanoseconds, jb::defaults::max_messages_per_microsecond, jb::defaults::max_messages_per_millisecond, jb::defaults::max_messages_per_second, jb::defaults::max_processing_latency_nanoseconds, and jb::defaults::reporting_interval_seconds.
BOOST_AUTO_TEST_CASE() [4/4]
BOOST_AUTO_TEST_CASE (offline_feed_statististics_coverage)
Test:
Test corner cases in jb::offline_feed_statistics to improve code coverage.
Definition at line 88 of file ut_offline_feed_statistics.cpp.
References jb::offline_feed_statistics::log_final_progress(), and jb::offline_feed_statistics::sample().