JayBeams: jb/ut_p2ceil.cpp File Reference
ut_p2ceil.cpp File Reference
#include <jb/p2ceil.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (p2ceil_simple_64)
BOOST_AUTO_TEST_CASE (p2ceil_compile_time)
BOOST_AUTO_TEST_CASE (p2ceil_simple_32)
BOOST_AUTO_TEST_CASE (p2ceil_simple_16)
BOOST_AUTO_TEST_CASE (p2ceil_simple_8)
Function Documentation
BOOST_AUTO_TEST_CASE (p2ceil_simple_64)
Test:
Verify that p2ceil works correctly for 64-bit numbers.
Definition at line 8 of file ut_p2ceil.cpp.
References jb::p2ceil().
BOOST_AUTO_TEST_CASE (p2ceil_compile_time)
Test:
Verify that p2ceil is known at compile-time.
Definition at line 19 of file ut_p2ceil.cpp.
References jb::p2ceil().
BOOST_AUTO_TEST_CASE (p2ceil_simple_32)
Test:
Verify that p2ceil works correctly for 32-bit numbers.
Definition at line 28 of file ut_p2ceil.cpp.
References jb::p2ceil().
BOOST_AUTO_TEST_CASE (p2ceil_simple_16)
Test:
Verify that p2ceil works correctly for 16-bit numbers.
Definition at line 39 of file ut_p2ceil.cpp.
References jb::p2ceil().
BOOST_AUTO_TEST_CASE (p2ceil_simple_8)
Test:
Verify that p2ceil works correctly for 8-bit numbers.
Definition at line 50 of file ut_p2ceil.cpp.
References jb::p2ceil().