JayBeams: jb/fftw/ut_time_delay_estimator.cpp File Reference
ut_time_delay_estimator.cpp File Reference
#include <jb/fftw/time_delay_estimator.hpp>
#include <jb/testing/create_square_timeseries.hpp>
#include <jb/testing/delay_timeseries.hpp>
#include <boost/test/unit_test.hpp>
#include <chrono>
Functions
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_simple)
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_error)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/2]
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_simple)
Test:
Verify that we can create and use a simple time delay estimator.
Definition at line 11 of file ut_time_delay_estimator.cpp.
References jb::testing::create_square_timeseries(), jb::testing::delay_timeseries_periodic(), and jb::detail::nsamples().
BOOST_AUTO_TEST_CASE() [2/2]
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_error)
Test:
Verify that jb::fftw::time_delay_estimator can handle edge conditions.
Definition at line 33 of file ut_time_delay_estimator.cpp.
References jb::detail::nsamples().