JayBeams: jb/itch5/ut_stock_directory_message.cpp File Reference
ut_stock_directory_message.cpp File Reference
#include <jb/itch5/stock_directory_message.hpp>
#include <jb/itch5/testing/data.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (decode_stock_directory_message)
BOOST_AUTO_TEST_CASE (stream_stock_directory_message)
BOOST_AUTO_TEST_CASE (simple_market_category)
BOOST_AUTO_TEST_CASE (simple_financial_status_indicator)
BOOST_AUTO_TEST_CASE (simple_roundlots_only)
BOOST_AUTO_TEST_CASE (simple_issue_classification)
BOOST_AUTO_TEST_CASE (simple_short_sale_threshold_indicator)
BOOST_AUTO_TEST_CASE (simple_luld_reference_price_tier)
BOOST_AUTO_TEST_CASE (simple_etp_flag)
BOOST_AUTO_TEST_CASE (simple_inverse_indicator)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/10]
BOOST_AUTO_TEST_CASE (decode_stock_directory_message)
Test:
Verify that the jb::itch5::stock_directory_message decoder works as expected.
Definition at line 10 of file ut_stock_directory_message.cpp.
References jb::itch5::testing::expected_ts(), jb::itch5::stock_directory_message::message_type, jb::itch5::decoder< validate, T >::r(), and jb::itch5::testing::stock_directory().
BOOST_AUTO_TEST_CASE() [2/10]
BOOST_AUTO_TEST_CASE (stream_stock_directory_message)
Test:
Verify that jb::itch5::stock_directory_message iostream operator works as expected.
Definition at line 64 of file ut_stock_directory_message.cpp.
References jb::itch5::decoder< validate, T >::r(), and jb::itch5::testing::stock_directory().
BOOST_AUTO_TEST_CASE() [3/10]
BOOST_AUTO_TEST_CASE (simple_market_category)
Test:
Verify that market_category_t works as expected.
Definition at line 95 of file ut_stock_directory_message.cpp.
BOOST_AUTO_TEST_CASE() [4/10]
BOOST_AUTO_TEST_CASE (simple_financial_status_indicator)
Test:
Verify that financial_status_indicator_t works as expected.
Definition at line 111 of file ut_stock_directory_message.cpp.
BOOST_AUTO_TEST_CASE() [5/10]
BOOST_AUTO_TEST_CASE (simple_roundlots_only)
Test:
Verify that roundlots_only_t works as expected.
Definition at line 122 of file ut_stock_directory_message.cpp.
BOOST_AUTO_TEST_CASE() [6/10]
BOOST_AUTO_TEST_CASE (simple_issue_classification)
Test:
Verify that issue_classification_t works as expected.
Definition at line 132 of file ut_stock_directory_message.cpp.
BOOST_AUTO_TEST_CASE() [7/10]
BOOST_AUTO_TEST_CASE (simple_short_sale_threshold_indicator)
Test:
Verify that short_sale_threshold_indicator_t works as expected.
Definition at line 143 of file ut_stock_directory_message.cpp.
BOOST_AUTO_TEST_CASE() [8/10]
BOOST_AUTO_TEST_CASE (simple_luld_reference_price_tier)
Test:
Verify that luld_reference_price_tier_t works as expected.
Definition at line 154 of file ut_stock_directory_message.cpp.
BOOST_AUTO_TEST_CASE() [9/10]
BOOST_AUTO_TEST_CASE (simple_etp_flag)
Test:
Verify that etp_flag_t works as expected.
Definition at line 165 of file ut_stock_directory_message.cpp.
BOOST_AUTO_TEST_CASE() [10/10]
BOOST_AUTO_TEST_CASE (simple_inverse_indicator)
Test:
Verify that inverse_indicator_t works as expected.
Definition at line 176 of file ut_stock_directory_message.cpp.