JayBeams: jb/itch5/ut_process_buffer_mlist.cpp File Reference
ut_process_buffer_mlist.cpp File Reference
#include <jb/itch5/add_order_message.hpp>
#include <jb/itch5/process_buffer_mlist.hpp>
#include <jb/itch5/stock_directory_message.hpp>
#include <jb/itch5/system_event_message.hpp>
#include <jb/itch5/testing/data.hpp>
#include <jb/gmock/init.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (process_buffer_mlist_empty)
Verify that jb::itch5::process_buffer_mlist<> works for empty lists.
BOOST_AUTO_TEST_CASE (process_buffer_mlist_single)
Verify that jb::itch5::process_buffer_mlist<> works for a list with a single element.
BOOST_AUTO_TEST_CASE (process_buffer_mlist_3)
Verify that jb::itch5::process_buffer_mlist<> works for a list with 3 elements.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/3]
BOOST_AUTO_TEST_CASE (process_buffer_mlist_empty)
Verify that jb::itch5::process_buffer_mlist<> works for empty lists.
Definition at line 45 of file ut_process_buffer_mlist.cpp.
References jb::itch5::testing::system_event().
BOOST_AUTO_TEST_CASE() [2/3]
BOOST_AUTO_TEST_CASE (process_buffer_mlist_single)
Verify that jb::itch5::process_buffer_mlist<> works for a list with a single element.
Definition at line 59 of file ut_process_buffer_mlist.cpp.
References jb::itch5::testing::stock_directory(), and jb::itch5::testing::system_event().
BOOST_AUTO_TEST_CASE() [3/3]
BOOST_AUTO_TEST_CASE (process_buffer_mlist_3)
Verify that jb::itch5::process_buffer_mlist<> works for a list with 3 elements.
Definition at line 87 of file ut_process_buffer_mlist.cpp.
References jb::itch5::testing::add_order(), jb::itch5::testing::stock_directory(), and jb::itch5::testing::system_event().