JayBeams: jb/ut_logging.cpp File Reference
ut_logging.cpp File Reference
#include <jb/as_hhmmss.hpp>
#include <jb/log.hpp>
#include <boost/log/sinks/sync_frontend.hpp>
#include <boost/log/sinks/text_ostream_backend.hpp>
#include <boost/test/unit_test.hpp>
#include <sstream>
Functions
BOOST_AUTO_TEST_CASE (logging_basic)
BOOST_AUTO_TEST_CASE (logging_yaml)
BOOST_AUTO_TEST_CASE (logging_config_errors)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/3]
BOOST_AUTO_TEST_CASE (logging_basic)
Test:
Verify that basic logging functions work as expected.
Definition at line 12 of file ut_logging.cpp.
References jb::debug, jb::log::defaults::enable_file_logging, jb::log::init(), JB_LOG, jb::log::defaults::minimum_severity, jb::log::next_tid(), and jb::warning.
BOOST_AUTO_TEST_CASE() [2/3]
BOOST_AUTO_TEST_CASE (logging_yaml)
Test:
Verify that parsing YAML files to configure logging works as expected.
Definition at line 76 of file ut_logging.cpp.
References jb::error, jb::config_object::load_overrides(), jb::log::config::minimum_console_severity, jb::log::config::minimum_severity, and jb::notice.
BOOST_AUTO_TEST_CASE() [3/3]
BOOST_AUTO_TEST_CASE (logging_config_errors)
Test:
Verify that configuration errors are detected.
Definition at line 97 of file ut_logging.cpp.
References jb::config_object::load_overrides().