JayBeams: jb/itch5/ut_check_offset.cpp File Reference
ut_check_offset.cpp File Reference
#include <jb/itch5/decoder.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (check_offset_disabled)
BOOST_AUTO_TEST_CASE (check_offset_enabled)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/2]
BOOST_AUTO_TEST_CASE (check_offset_disabled)
Test:
Verify that buffer size validation works as expected.
Definition at line 8 of file ut_check_offset.cpp.
References jb::itch5::check_offset().
BOOST_AUTO_TEST_CASE() [2/2]
BOOST_AUTO_TEST_CASE (check_offset_enabled)
Test:
Verify that buffer size validation works as expected.
Definition at line 22 of file ut_check_offset.cpp.
References jb::itch5::check_offset(), and jb::itch5::check_offset< true >().