JayBeams: jb/itch5/ut_order_executed_price_message.cpp File Reference
ut_order_executed_price_message.cpp File Reference
#include <jb/itch5/order_executed_price_message.hpp>
#include <jb/itch5/testing/data.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (decode_order_executed_price_message)
BOOST_AUTO_TEST_CASE (stream_order_executed_price_message)
Function Documentation
BOOST_AUTO_TEST_CASE (decode_order_executed_price_message)
Test:
Verify that the jb::itch5::order_executed_price_message decoder works as expected.
Definition at line 10 of file ut_order_executed_price_message.cpp.
References jb::itch5::testing::expected_ts(), jb::itch5::order_executed_price_message::message_type, jb::itch5::testing::order_executed_price(), and jb::itch5::decoder< validate, T >::r().
BOOST_AUTO_TEST_CASE (stream_order_executed_price_message)
Test:
Verify that jb::itch5::order_executed_price_message iostream operator works as expected.
Definition at line 48 of file ut_order_executed_price_message.cpp.
References jb::itch5::testing::order_executed_price(), and jb::itch5::decoder< validate, T >::r().