JayBeams: jb/itch5/ut_make_socket_udp_send.cpp File Reference
ut_make_socket_udp_send.cpp File Reference
#include <jb/itch5/make_socket_udp_send.hpp>
#include <jb/itch5/testing/mock_udp_socket.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_send_compile)
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_send_basic)
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_send_multicast_ipv4)
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_send_multicast_ipv6)
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_send_multicast_options)
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_send_multicast_options_errors)
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_send_unicast_options)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/7]
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_send_compile)
Test:
Verify that jb::itch5::make_socket_udp_send compiles.
Definition at line 7 of file ut_make_socket_udp_send.cpp.
References jb::itch5::udp_sender_config::address, and jb::itch5::make_socket_udp_send().
BOOST_AUTO_TEST_CASE() [2/7]
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_send_basic)
Test:
Create a simple unicast socket on the default interface
Definition at line 18 of file ut_make_socket_udp_send.cpp.
References jb::itch5::detail::setup_socket_udp_send().
BOOST_AUTO_TEST_CASE() [3/7]
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_send_multicast_ipv4)
Test:
Create a IPv4 multicast socket on the default interface.
Definition at line 35 of file ut_make_socket_udp_send.cpp.
References jb::itch5::detail::setup_socket_udp_send().
BOOST_AUTO_TEST_CASE() [4/7]
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_send_multicast_ipv6)
Test:
Create a IPv6 multicast socket on the default interface.
Definition at line 54 of file ut_make_socket_udp_send.cpp.
References jb::itch5::detail::setup_socket_udp_send().
BOOST_AUTO_TEST_CASE() [5/7]
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_send_multicast_options)
Test:
Create a multicast socket on an specific interface ...
Definition at line 72 of file ut_make_socket_udp_send.cpp.
References jb::itch5::detail::setup_socket_udp_send().
BOOST_AUTO_TEST_CASE() [6/7]
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_send_multicast_options_errors)
Test:
Create a multicast socket on an specific interface.
Definition at line 119 of file ut_make_socket_udp_send.cpp.
References jb::itch5::make_socket_udp_send().
BOOST_AUTO_TEST_CASE() [7/7]
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_send_unicast_options)
Test:
Create a multicast socket on an specific interface.
Definition at line 133 of file ut_make_socket_udp_send.cpp.
References jb::itch5::detail::setup_socket_udp_send().