JayBeams: jb/ut_config_files_location.cpp File Reference
ut_config_files_location.cpp File Reference
#include <jb/gmock/init.hpp>
#include <jb/config_files_location.hpp>
#include <boost/filesystem/operations.hpp>
#include <boost/test/unit_test.hpp>
Namespaces
boost
boost::filesystem
Functions
void boost::filesystem::PrintTo (path const &p, ::std::ostream *os)
BOOST_AUTO_TEST_CASE (config_files_location_constructors)
BOOST_AUTO_TEST_CASE (config_files_location_program_root)
BOOST_AUTO_TEST_CASE (config_files_location_no_program_root)
BOOST_AUTO_TEST_CASE (config_files_location_undefined_undef_test_root)
BOOST_AUTO_TEST_CASE (config_files_location_undefined_undef_system_root)
BOOST_AUTO_TEST_CASE (config_files_location_installed_binary)
BOOST_AUTO_TEST_CASE (config_files_location_no_program_path)
BOOST_AUTO_TEST_CASE (config_files_location_find)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/8]
BOOST_AUTO_TEST_CASE (config_files_location_constructors)
Test:
Verify that the common constructors compile.
Definition at line 40 of file ut_config_files_location.cpp.
BOOST_AUTO_TEST_CASE() [2/8]
BOOST_AUTO_TEST_CASE (config_files_location_program_root)
Test:
Verify that a simple config_files_locations<> works as expected.
Definition at line 123 of file ut_config_files_location.cpp.
References jb::sysconfdir().
BOOST_AUTO_TEST_CASE() [3/8]
BOOST_AUTO_TEST_CASE (config_files_location_no_program_root)
Test:
Verify that a simple config_files_locations<> works without a program root.
Definition at line 144 of file ut_config_files_location.cpp.
References jb::sysconfdir().
BOOST_AUTO_TEST_CASE() [4/8]
BOOST_AUTO_TEST_CASE (config_files_location_undefined_undef_test_root)
Test:
Verify that a simple config_files_locations<> works with some variables undefined.
Definition at line 165 of file ut_config_files_location.cpp.
References jb::sysconfdir().
BOOST_AUTO_TEST_CASE() [5/8]
BOOST_AUTO_TEST_CASE (config_files_location_undefined_undef_system_root)
Test:
Verify that a simple config_files_locations<> works with some variables undefined.
Definition at line 186 of file ut_config_files_location.cpp.
References jb::sysconfdir().
BOOST_AUTO_TEST_CASE() [6/8]
BOOST_AUTO_TEST_CASE (config_files_location_installed_binary)
Test:
Verify that a simple config with a valid path for the binary works.
Definition at line 206 of file ut_config_files_location.cpp.
References jb::bindir(), and jb::sysconfdir().
BOOST_AUTO_TEST_CASE() [7/8]
BOOST_AUTO_TEST_CASE (config_files_location_no_program_path)
Test:
Verify that a simple config_files_locations<> works when the program is not path.
Definition at line 231 of file ut_config_files_location.cpp.
References jb::sysconfdir().
BOOST_AUTO_TEST_CASE() [8/8]
BOOST_AUTO_TEST_CASE (config_files_location_find)
Test:
Verify that the search algorithm works as expected.
Definition at line 249 of file ut_config_files_location.cpp.
References jb::bindir(), and jb::sysconfdir().