JayBeams: jb/itch5/ut_message_header.cpp File Reference
ut_message_header.cpp File Reference
#include <jb/itch5/message_header.hpp>
#include <jb/itch5/testing/data.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (decode_message_header)
BOOST_AUTO_TEST_CASE (stream_message_header)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/2]
BOOST_AUTO_TEST_CASE (decode_message_header)
Test:
Verify that jb::itch5::message_header decoder works as expected.
Definition at line 9 of file ut_message_header.cpp.
References jb::itch5::testing::expected_ts(), and jb::itch5::testing::message_header().
BOOST_AUTO_TEST_CASE() [2/2]
BOOST_AUTO_TEST_CASE (stream_message_header)
Test:
Verify that jb::itch5::message_header iostream operator works as expected.
Definition at line 34 of file ut_message_header.cpp.
References jb::itch5::testing::message_header().