JayBeams: jb/fftw/ut_time_delay_estimator_many.cpp File Reference
ut_time_delay_estimator_many.cpp File Reference
#include <jb/fftw/aligned_vector.hpp>
#include <jb/fftw/time_delay_estimator_many.hpp>
#include <jb/testing/check_close_enough.hpp>
#include <jb/testing/create_square_timeseries.hpp>
#include <jb/testing/create_triangle_timeseries.hpp>
#include <jb/testing/delay_timeseries.hpp>
#include <jb/testing/sum_square.hpp>
#include <boost/test/unit_test.hpp>
#include <chrono>
#include <complex>
Functions
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_3_dim_tde_with_0)
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_3_dim_tde_delay_0)
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_3_dim_tde_float)
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_2_dim_tde_float)
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_1_dim_tde_float)
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_vector_tde_float)
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_3_dim_tde_double)
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_2_dim_tde_double)
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_1_dim_tde_double)
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_vector_tde_double)
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_3_dim_tde_complex_float)
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_2_dim_tde_complex_float)
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_1_dim_tde_complex_float)
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_vector_tde_complex_float)
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_3_dim_tde_complex_double)
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_2_dim_tde_complex_double)
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_1_dim_tde_complex_double)
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_vector_tde_complex_double)
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_errors)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/19]
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_3_dim_tde_with_0)
Test:
Verify that FTE handles a timeseries filled with 0 dimension 3
Definition at line 17 of file ut_time_delay_estimator_many.cpp.
References jb::testing::check_collection_close_enough(), and jb::detail::nsamples().
BOOST_AUTO_TEST_CASE() [2/19]
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_3_dim_tde_delay_0)
Test:
Verify TDE handles exact same timeseries, delay = 0 dimension 3
Definition at line 74 of file ut_time_delay_estimator_many.cpp.
References jb::testing::check_collection_close_enough(), jb::testing::create_triangle_timeseries(), jb::detail::nsamples(), and jb::testing::sum_square().
BOOST_AUTO_TEST_CASE() [3/19]
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_3_dim_tde_float)
Test:
Verify that we can create and use a simple time delay estimator multi array dimension 3, with float value.
Definition at line 153 of file ut_time_delay_estimator_many.cpp.
References jb::testing::check_collection_close_enough(), jb::testing::create_triangle_timeseries(), jb::detail::nsamples(), and jb::testing::sum_square().
BOOST_AUTO_TEST_CASE() [4/19]
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_2_dim_tde_float)
Test:
Verify that we can create and use a simple time delay estimator multi array dimension 2, with float values.
Definition at line 223 of file ut_time_delay_estimator_many.cpp.
References jb::testing::check_collection_close_enough(), jb::testing::create_triangle_timeseries(), jb::detail::nsamples(), and jb::testing::sum_square().
BOOST_AUTO_TEST_CASE() [5/19]
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_1_dim_tde_float)
Test:
Verify that we can create and use a simple time delay estimator multi_array dimension 1 with float values.
Definition at line 290 of file ut_time_delay_estimator_many.cpp.
References jb::testing::check_collection_close_enough(), jb::testing::create_triangle_timeseries(), jb::detail::nsamples(), and jb::testing::sum_square().
BOOST_AUTO_TEST_CASE() [6/19]
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_vector_tde_float)
Test:
Verify that we can create and use a simple time delay estimator based on jb::fftw::aligned_vector timeseries with float values.
Definition at line 352 of file ut_time_delay_estimator_many.cpp.
References jb::testing::check_collection_close_enough(), jb::testing::create_triangle_timeseries(), jb::detail::nsamples(), and jb::testing::sum_square().
BOOST_AUTO_TEST_CASE() [7/19]
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_3_dim_tde_double)
Test:
Verify that we can create and use a simple time delay estimator multi array dimension 3, with double value.
Definition at line 414 of file ut_time_delay_estimator_many.cpp.
References jb::testing::check_collection_close_enough(), jb::testing::create_triangle_timeseries(), jb::detail::nsamples(), and jb::testing::sum_square().
BOOST_AUTO_TEST_CASE() [8/19]
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_2_dim_tde_double)
Test:
Verify that we can create and use a simple time delay estimator multi array dimension 2, with double values.
Definition at line 483 of file ut_time_delay_estimator_many.cpp.
References jb::testing::check_collection_close_enough(), jb::testing::create_triangle_timeseries(), jb::detail::nsamples(), and jb::testing::sum_square().
BOOST_AUTO_TEST_CASE() [9/19]
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_1_dim_tde_double)
Test:
Verify that we can create and use a simple time delay estimator multi_array dimension 1 with double values.
Definition at line 549 of file ut_time_delay_estimator_many.cpp.
References jb::testing::check_collection_close_enough(), jb::testing::create_triangle_timeseries(), jb::detail::nsamples(), and jb::testing::sum_square().
BOOST_AUTO_TEST_CASE() [10/19]
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_vector_tde_double)
Test:
Verify that we can create and use a simple time delay estimator based on std::vector timeseries with double values.
Definition at line 610 of file ut_time_delay_estimator_many.cpp.
References jb::testing::check_collection_close_enough(), jb::testing::create_triangle_timeseries(), jb::detail::nsamples(), and jb::testing::sum_square().
BOOST_AUTO_TEST_CASE() [11/19]
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_3_dim_tde_complex_float)
Test:
Verify that we can create and use a simple time delay estimator multi array dimension 3, with std::complex<float> value.
Definition at line 671 of file ut_time_delay_estimator_many.cpp.
References jb::testing::check_collection_close_enough(), jb::testing::create_triangle_timeseries(), jb::detail::nsamples(), and jb::testing::sum_square().
BOOST_AUTO_TEST_CASE() [12/19]
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_2_dim_tde_complex_float)
Test:
Verify that we can create and use a simple time delay estimator multi array dimension 2, with std::complex<float> values.
Definition at line 741 of file ut_time_delay_estimator_many.cpp.
References jb::testing::check_collection_close_enough(), jb::testing::create_triangle_timeseries(), jb::detail::nsamples(), and jb::testing::sum_square().
BOOST_AUTO_TEST_CASE() [13/19]
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_1_dim_tde_complex_float)
Test:
Verify that we can create and use a simple time delay estimator multi_array dimension 1 with std::complex<float> values.
Definition at line 808 of file ut_time_delay_estimator_many.cpp.
References jb::testing::check_collection_close_enough(), jb::testing::create_triangle_timeseries(), jb::detail::nsamples(), and jb::testing::sum_square().
BOOST_AUTO_TEST_CASE() [14/19]
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_vector_tde_complex_float)
Test:
Verify that we can create and use a simple time delay estimator based on std::vector timeseries with std::complex<float> values.
Definition at line 870 of file ut_time_delay_estimator_many.cpp.
References jb::testing::check_collection_close_enough(), jb::testing::create_triangle_timeseries(), jb::detail::nsamples(), and jb::testing::sum_square().
BOOST_AUTO_TEST_CASE() [15/19]
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_3_dim_tde_complex_double)
Test:
Verify that we can create and use a simple time delay estimator multi array dimension 3, with std::complex<double> value.
Definition at line 931 of file ut_time_delay_estimator_many.cpp.
References jb::testing::check_collection_close_enough(), jb::testing::create_triangle_timeseries(), jb::detail::nsamples(), and jb::testing::sum_square().
BOOST_AUTO_TEST_CASE() [16/19]
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_2_dim_tde_complex_double)
Test:
Verify that we can create and use a simple time delay estimator multi array dimension 2, with std::complex<double> values.
Definition at line 1000 of file ut_time_delay_estimator_many.cpp.
References jb::testing::check_collection_close_enough(), jb::testing::create_triangle_timeseries(), jb::detail::nsamples(), and jb::testing::sum_square().
BOOST_AUTO_TEST_CASE() [17/19]
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_1_dim_tde_complex_double)
Test:
Verify that we can create and use a simple time delay estimator multi_array dimension 1 with std::complex<double> values.
Definition at line 1066 of file ut_time_delay_estimator_many.cpp.
References jb::testing::check_collection_close_enough(), jb::testing::create_triangle_timeseries(), jb::detail::nsamples(), and jb::testing::sum_square().
BOOST_AUTO_TEST_CASE() [18/19]
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_vector_tde_complex_double)
Test:
Verify that we can create and use a simple time delay estimator based on std::vector timeseries with std::complex<double> values.
Definition at line 1127 of file ut_time_delay_estimator_many.cpp.
References jb::testing::check_collection_close_enough(), jb::testing::create_triangle_timeseries(), jb::detail::nsamples(), and jb::testing::sum_square().
BOOST_AUTO_TEST_CASE() [19/19]
BOOST_AUTO_TEST_CASE (fftw_time_delay_estimator_many_errors)
Test:
Verify thattime delay estimator handles errors
Definition at line 1187 of file ut_time_delay_estimator_many.cpp.
References jb::detail::nsamples().