JayBeams: jb/itch5/ut_add_order_message.cpp File Reference
ut_add_order_message.cpp File Reference
#include <jb/itch5/add_order_message.hpp>
#include <jb/itch5/testing/data.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (decode_add_order_message)
BOOST_AUTO_TEST_CASE (stream_add_order_message)
BOOST_AUTO_TEST_CASE (simple_buy_sell_indicator)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/3]
BOOST_AUTO_TEST_CASE (decode_add_order_message)
Test:
Verify that the jb::itch5::add_order_message decoder works as expected.
Definition at line 10 of file ut_add_order_message.cpp.
References jb::itch5::testing::add_order(), jb::itch5::testing::expected_ts(), jb::itch5::add_order_message::message_type, and jb::itch5::decoder< validate, T >::r().
BOOST_AUTO_TEST_CASE() [2/3]
BOOST_AUTO_TEST_CASE (stream_add_order_message)
Test:
Verify that jb::itch5::add_order_message iostream operator works as expected.
Definition at line 44 of file ut_add_order_message.cpp.
References jb::itch5::testing::add_order(), and jb::itch5::decoder< validate, T >::r().
BOOST_AUTO_TEST_CASE() [3/3]
BOOST_AUTO_TEST_CASE (simple_buy_sell_indicator)
Test:
Verify that buy_sell_indicator_t works as expected.
Definition at line 65 of file ut_add_order_message.cpp.