JayBeams: jb/itch5/ut_order_delete_message.cpp File Reference
ut_order_delete_message.cpp File Reference
#include <jb/itch5/order_delete_message.hpp>
#include <jb/itch5/testing/data.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (decode_order_delete_message)
BOOST_AUTO_TEST_CASE (stream_order_delete_message)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/2]
BOOST_AUTO_TEST_CASE (decode_order_delete_message)
Test:
Verify that the jb::itch5::order_delete_message decoder works as expected.
Definition at line 10 of file ut_order_delete_message.cpp.
References jb::itch5::testing::expected_ts(), jb::itch5::order_delete_message::message_type, jb::itch5::testing::order_delete(), and jb::itch5::decoder< validate, T >::r().
BOOST_AUTO_TEST_CASE() [2/2]
BOOST_AUTO_TEST_CASE (stream_order_delete_message)
Test:
Verify that jb::itch5::order_delete_message iostream operator works as expected.
Definition at line 37 of file ut_order_delete_message.cpp.
References jb::itch5::testing::order_delete(), and jb::itch5::decoder< validate, T >::r().