JayBeams: jb/testing/ut_check_close_enough.cpp File Reference
ut_check_close_enough.cpp File Reference
#include <jb/testing/check_close_enough.hpp>
#include <boost/test/unit_test.hpp>
#include <complex>
Functions
BOOST_AUTO_TEST_CASE (check_close_enough_integer)
BOOST_AUTO_TEST_CASE (check_close_enough_float)
BOOST_AUTO_TEST_CASE (check_close_enough_double)
BOOST_AUTO_TEST_CASE (check_close_enough_complex_integer)
BOOST_AUTO_TEST_CASE (check_close_enough_float_vector)
BOOST_AUTO_TEST_CASE_EXPECTED_FAILURES (check_close_enough_float_vector_failure, JB_TESTING_MAX_DIFFERENCES_PRINTED)
BOOST_AUTO_TEST_CASE_EXPECTED_FAILURES (check_close_enough_complex_double_multi_array, JB_TESTING_MAX_DIFFERENCES_PRINTED)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/5]
BOOST_AUTO_TEST_CASE (check_close_enough_integer)
Test:
check_close_enough functionality for integer type
Usually I do not spend time testing helper functions for tests, but in this case the helper has a lot of template code and we want to validate this before too long.
Definition at line 13 of file ut_check_close_enough.cpp.
References jb::testing::check_close_enough().
BOOST_AUTO_TEST_CASE() [2/5]
BOOST_AUTO_TEST_CASE (check_close_enough_float)
Test:
check_close_enough functionality for float type
Definition at line 31 of file ut_check_close_enough.cpp.
References jb::testing::check_close_enough().
BOOST_AUTO_TEST_CASE() [3/5]
BOOST_AUTO_TEST_CASE (check_close_enough_double)
Test:
check_close_enough functionality for double type
Definition at line 49 of file ut_check_close_enough.cpp.
References jb::testing::check_close_enough().
BOOST_AUTO_TEST_CASE() [4/5]
BOOST_AUTO_TEST_CASE (check_close_enough_complex_integer)
Test:
check_close_enough functionality for complex of integer type
Definition at line 67 of file ut_check_close_enough.cpp.
References jb::testing::check_close_enough().
BOOST_AUTO_TEST_CASE() [5/5]
BOOST_AUTO_TEST_CASE (check_close_enough_float_vector)
Test:
check_close_enough functionality for vector of float type
Definition at line 87 of file ut_check_close_enough.cpp.
References jb::testing::check_collection_close_enough(), and jb::detail::nsamples().
BOOST_AUTO_TEST_CASE_EXPECTED_FAILURES() [1/2]
BOOST_AUTO_TEST_CASE_EXPECTED_FAILURES (check_close_enough_float_vector_failure , JB_TESTING_MAX_DIFFERENCES_PRINTED)
Test:
check_close_enough functionality for vector of float type
TODO(#93) cleanup after boost-1.58.0 is no longer supported.
Definition at line 108 of file ut_check_close_enough.cpp.
References jb::testing::check_collection_close_enough(), and jb::detail::nsamples().
BOOST_AUTO_TEST_CASE_EXPECTED_FAILURES() [2/2]
BOOST_AUTO_TEST_CASE_EXPECTED_FAILURES (check_close_enough_complex_double_multi_array , JB_TESTING_MAX_DIFFERENCES_PRINTED)
Test:
check_close_enough functionality for multi_array of 3 dimension complex double type
TODO(#93) cleanup after boost-1.58.0 is no longer supported.
Definition at line 141 of file ut_check_close_enough.cpp.
References jb::testing::check_collection_close_enough(), and jb::detail::nsamples().