JayBeams: jb/ehs/ut_request_dispatcher.cpp File Reference
ut_request_dispatcher.cpp File Reference
#include <jb/ehs/request_dispatcher.hpp>
#include <jb/strtonum.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (request_dispatcher_base)
BOOST_AUTO_TEST_CASE (request_dispatcher_error)
BOOST_AUTO_TEST_CASE (request_dispatcher_counter)
BOOST_AUTO_TEST_CASE (request_dispatcher_network_counter)
BOOST_AUTO_TEST_CASE (request_dispatcher_append_metrics)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/5]
BOOST_AUTO_TEST_CASE (request_dispatcher_base)
Test:
Verify that jb::ehs::request_dispatcher works as expected.
Definition at line 9 of file ut_request_dispatcher.cpp.
References jb::ehs::request_dispatcher::add_handler(), and jb::ehs::request_dispatcher::process().
BOOST_AUTO_TEST_CASE() [2/5]
BOOST_AUTO_TEST_CASE (request_dispatcher_error)
Test:
Verify that jb::ehs::request_dispatcher works as expected for errors.
Definition at line 56 of file ut_request_dispatcher.cpp.
References jb::ehs::request_dispatcher::add_handler(), jb::ehs::request_dispatcher::get_write_500(), and jb::ehs::request_dispatcher::process().
BOOST_AUTO_TEST_CASE() [3/5]
BOOST_AUTO_TEST_CASE (request_dispatcher_counter)
Test:
Verify that jb::ehs::request_dispatcher counters work as expected.
Definition at line 84 of file ut_request_dispatcher.cpp.
References jb::ehs::request_dispatcher::add_handler(), jb::ehs::request_dispatcher::get_write_100(), jb::ehs::request_dispatcher::get_write_200(), jb::ehs::request_dispatcher::get_write_300(), jb::ehs::request_dispatcher::get_write_400(), jb::ehs::request_dispatcher::get_write_500(), jb::ehs::request_dispatcher::get_write_invalid(), jb::ehs::request_dispatcher::process(), and jb::strtonum().
BOOST_AUTO_TEST_CASE() [4/5]
BOOST_AUTO_TEST_CASE (request_dispatcher_network_counter)
Test:
Verify that jb::ehs::request_dispatcher counters work as expected.
Definition at line 154 of file ut_request_dispatcher.cpp.
References jb::ehs::request_dispatcher::count_accept_error(), jb::ehs::request_dispatcher::count_accept_ok(), jb::ehs::request_dispatcher::count_close_connection(), jb::ehs::request_dispatcher::count_open_connection(), jb::ehs::request_dispatcher::count_read_error(), jb::ehs::request_dispatcher::count_read_ok(), jb::ehs::request_dispatcher::count_write_error(), jb::ehs::request_dispatcher::count_write_ok(), jb::ehs::request_dispatcher::get_accept_error(), jb::ehs::request_dispatcher::get_accept_ok(), jb::ehs::request_dispatcher::get_close_connection(), jb::ehs::request_dispatcher::get_open_connection(), jb::ehs::request_dispatcher::get_read_error(), jb::ehs::request_dispatcher::get_read_ok(), jb::ehs::request_dispatcher::get_write_error(), and jb::ehs::request_dispatcher::get_write_ok().
BOOST_AUTO_TEST_CASE() [5/5]
BOOST_AUTO_TEST_CASE (request_dispatcher_append_metrics)
Test:
Verify that jb::ehs::request_dispatcher::append_metrics works as expected
Definition at line 205 of file ut_request_dispatcher.cpp.
References jb::ehs::request_dispatcher::append_metrics().