JayBeams: jb/ut_thread_config.cpp File Reference
ut_thread_config.cpp File Reference
#include <jb/thread_config.hpp>
#include <boost/test/unit_test.hpp>
#include <sched.h>
Functions
BOOST_AUTO_TEST_CASE (thread_config_basic)
BOOST_AUTO_TEST_CASE (thread_config_scheduling_policy)
BOOST_AUTO_TEST_CASE (thread_config_scheduling_priority)
BOOST_AUTO_TEST_CASE (thread_config_overrides)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/4]
BOOST_AUTO_TEST_CASE (thread_config_basic)
Test:
Verify that basic functionality works as expected.
Definition at line 10 of file ut_thread_config.cpp.
References jb::thread_config::name, jb::thread_config::native_priority(), jb::thread_config::native_scheduling_policy(), and jb::thread_config::scheduler.
BOOST_AUTO_TEST_CASE() [2/4]
BOOST_AUTO_TEST_CASE (thread_config_scheduling_policy)
Test:
Verify that setting the scheduling policy works as expected
Definition at line 26 of file ut_thread_config.cpp.
References jb::thread_config::native_scheduling_policy(), and jb::thread_config::scheduler.
BOOST_AUTO_TEST_CASE() [3/4]
BOOST_AUTO_TEST_CASE (thread_config_scheduling_priority)
Test:
Verify that setting the scheduling priority works as expected
Definition at line 41 of file ut_thread_config.cpp.
References jb::thread_config::native_priority(), jb::thread_config::priority, and jb::thread_config::scheduler.
BOOST_AUTO_TEST_CASE() [4/4]
BOOST_AUTO_TEST_CASE (thread_config_overrides)
Test:
Verify that parsing YAML overrides works as expected.
Definition at line 59 of file ut_thread_config.cpp.
References jb::thread_config::affinity, jb::config_object::load_overrides(), jb::thread_config::native_priority(), jb::thread_config::native_scheduling_policy(), and jb::cpu_set::set().