JayBeams: jb/itch5/ut_mold_udp_pacer.cpp File Reference
ut_mold_udp_pacer.cpp File Reference
#include <jb/itch5/mold_udp_pacer.hpp>
#include <jb/itch5/testing_data.hpp>
#include <boost/asio.hpp>
#include <boost/array.hpp>
#include <boost/test/unit_test.hpp>
#include <skye/mock_function.hpp>
Classes
struct mock_sink
A simple class to mock a suitable sink for jb::itch5::mold_udp_pacer.
struct mock_clock
Functions
BOOST_AUTO_TEST_CASE (itch5_mold_udp_pacer_basic)
BOOST_AUTO_TEST_CASE (itch5_mold_udp_pacer_coalesce)
BOOST_AUTO_TEST_CASE (itch5_mold_udp_pacer_flush_full)
BOOST_AUTO_TEST_CASE (itch5_mold_udp_pacer_flush_timeout)
BOOST_AUTO_TEST_CASE (itch5_mold_udp_pacer_flush_on_empty)
BOOST_AUTO_TEST_CASE (itch5_testing_create_message_errors)
Function Documentation
BOOST_AUTO_TEST_CASE (itch5_mold_udp_pacer_basic)
Test:
Verify that jb::itch5::mold_udp_pacer works as expected for a simple stream of messages.
Send 3 messages every 10 usecs, of different sizes and types
Definition at line 33 of file ut_mold_udp_pacer.cpp.
References jb::itch5::testing::create_message(), jb::itch5::mold_udp_pacer< clock_type >::handle_message(), jb::itch5::mold_udp_protocol::header_size, jb::itch5::mold_udp_pacer< clock_type >::heartbeat(), jb::itch5::defaults::maximum_delay_microseconds, mock_clock::now, and mock_sink::packets.
BOOST_AUTO_TEST_CASE (itch5_mold_udp_pacer_coalesce)
Test:
Verify that multiple back-to-back messages are grouped into a single packet.
Definition at line 76 of file ut_mold_udp_pacer.cpp.
References jb::itch5::testing::create_message(), jb::itch5::mold_udp_pacer< clock_type >::handle_message(), jb::itch5::mold_udp_protocol::header_size, jb::itch5::mold_udp_pacer< clock_type >::heartbeat(), jb::itch5::defaults::maximum_delay_microseconds, jb::itch5::defaults::maximum_transmission_unit, mock_clock::now, and mock_sink::packets.
BOOST_AUTO_TEST_CASE (itch5_mold_udp_pacer_flush_full)
Test:
Verify that multiple back-to-back messages are flushed if the packet is about to get full...
Definition at line 130 of file ut_mold_udp_pacer.cpp.
References jb::itch5::testing::create_message(), jb::itch5::mold_udp_pacer< clock_type >::handle_message(), jb::itch5::mold_udp_protocol::header_size, jb::itch5::mold_udp_pacer< clock_type >::heartbeat(), jb::itch5::defaults::maximum_delay_microseconds, jb::itch5::defaults::maximum_transmission_unit, mock_clock::now, and mock_sink::packets.
BOOST_AUTO_TEST_CASE (itch5_mold_udp_pacer_flush_timeout)
Test:
Verify that multiple back-to-back messages are flushed if the packet is about to get full...
Definition at line 187 of file ut_mold_udp_pacer.cpp.
References jb::itch5::testing::create_message(), jb::itch5::mold_udp_pacer< clock_type >::handle_message(), jb::itch5::mold_udp_protocol::header_size, jb::itch5::defaults::maximum_delay_microseconds, jb::itch5::defaults::maximum_transmission_unit, mock_clock::now, and mock_sink::packets.
BOOST_AUTO_TEST_CASE (itch5_mold_udp_pacer_flush_on_empty)
Test:
Verify that flush() on an empty packet does not produce a send() request.
Definition at line 245 of file ut_mold_udp_pacer.cpp.
References jb::itch5::testing::create_message(), jb::itch5::mold_udp_pacer< clock_type >::flush(), jb::itch5::mold_udp_pacer< clock_type >::handle_message(), jb::itch5::mold_udp_protocol::header_size, jb::itch5::mold_udp_pacer< clock_type >::heartbeat(), jb::itch5::defaults::maximum_delay_microseconds, jb::itch5::defaults::maximum_transmission_unit, mock_clock::now, and mock_sink::packets.
BOOST_AUTO_TEST_CASE (itch5_testing_create_message_errors)
Test:
Increase code coverage in jb::itch5::testing::create_message()
Definition at line 293 of file ut_mold_udp_pacer.cpp.
References jb::itch5::testing::create_message().