JayBeams: jb/tde/ut_generic_reduce.cpp File Reference
ut_generic_reduce.cpp File Reference
#include <jb/opencl/config.hpp>
#include <jb/opencl/copy_to_host_async.hpp>
#include <jb/opencl/device_selector.hpp>
#include <jb/tde/generic_reduce.hpp>
#include <jb/testing/check_close_enough.hpp>
#include <jb/testing/create_random_timeseries.hpp>
#include <jb/complex_traits.hpp>
#include <boost/compute/command_queue.hpp>
#include <boost/compute/container.hpp>
#include <boost/compute/context.hpp>
#include <boost/compute/type_traits.hpp>
#include <boost/compute/types/complex.hpp>
#include <boost/test/unit_test.hpp>
#include <memory>
#include <random>
#include <sstream>
Classes
class jb::tde::reduce_sum< T >
Namespaces
jb
The top-level namespace for the JayBeams library.
jb::tde
Functions
BOOST_AUTO_TEST_CASE (generic_reduce_int_2e6)
BOOST_AUTO_TEST_CASE (generic_reduce_int_2e13)
BOOST_AUTO_TEST_CASE (generic_reduce_int_2e20)
BOOST_AUTO_TEST_CASE (generic_reduce_int_1000000)
BOOST_AUTO_TEST_CASE (generic_reduce_int_PRIMES)
BOOST_AUTO_TEST_CASE (generic_reduce_float_PRIMES)
BOOST_AUTO_TEST_CASE (generic_reduce_complex_float_PRIMES)
BOOST_AUTO_TEST_CASE (generic_reduce_complex_double_PRIMES)
BOOST_AUTO_TEST_CASE (generic_reduce_complex_execute_error)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/9]
BOOST_AUTO_TEST_CASE (generic_reduce_int_2e6)
Test:
Make sure the jb::tde::generic_reduce() works as expected.for sizes around ~256, which is close to MAX_WORK_GROUP_SIZE
Definition at line 133 of file ut_generic_reduce.cpp.
References jb::testing::defaults::size.
Referenced by BOOST_AUTO_TEST_CASE().
BOOST_AUTO_TEST_CASE() [2/9]
BOOST_AUTO_TEST_CASE (generic_reduce_int_2e13)
Test:
Make sure the jb::tde::generic_reduce() works as expected.for sizes around ~256 * 32, which is close to MAX_WORK_GROUP_SIZE * MAX_COMPUTE_UNITS
Definition at line 146 of file ut_generic_reduce.cpp.
References jb::testing::defaults::size.
BOOST_AUTO_TEST_CASE() [3/9]
BOOST_AUTO_TEST_CASE (generic_reduce_int_2e20)
Test:
Make sure the jb::tde::generic_reduce() works as expected for 2^20 (1 million binary)
Definition at line 158 of file ut_generic_reduce.cpp.
References jb::testing::defaults::size.
BOOST_AUTO_TEST_CASE() [4/9]
BOOST_AUTO_TEST_CASE (generic_reduce_int_1000000)
Test:
Make sure the jb::tde::generic_reduce() works as expected for 1000000
Definition at line 167 of file ut_generic_reduce.cpp.
References jb::testing::defaults::size.
BOOST_AUTO_TEST_CASE() [5/9]
BOOST_AUTO_TEST_CASE (generic_reduce_int_PRIMES)
Test:
Make sure the jb::tde::generic_reduce() works as expected for a number that does not have a lot of powers of 2.
Definition at line 176 of file ut_generic_reduce.cpp.
References BOOST_AUTO_TEST_CASE(), jb::opencl::device_selector(), and jb::testing::defaults::size.
BOOST_AUTO_TEST_CASE() [6/9]
BOOST_AUTO_TEST_CASE (generic_reduce_float_PRIMES)
Test:
Make sure the jb::tde::generic_reduce() works as expected for a number without a lot of powers of 2
Definition at line 199 of file ut_generic_reduce.cpp.
References jb::testing::defaults::size.
BOOST_AUTO_TEST_CASE() [7/9]
BOOST_AUTO_TEST_CASE (generic_reduce_complex_float_PRIMES)
Test:
Make sure the jb::tde::generic_reduce() works as expected for a number without a lot of powers of 2
Definition at line 208 of file ut_generic_reduce.cpp.
References jb::testing::defaults::size.
BOOST_AUTO_TEST_CASE() [8/9]
BOOST_AUTO_TEST_CASE (generic_reduce_complex_double_PRIMES)
Test:
Make sure the jb::tde::generic_reduce() works as expected for a number without a lot of powers of 2
Definition at line 217 of file ut_generic_reduce.cpp.
References jb::testing::defaults::size.
BOOST_AUTO_TEST_CASE() [9/9]
BOOST_AUTO_TEST_CASE (generic_reduce_complex_execute_error)
Test:
Improve code coverage, test that invalid inputs in execute() are detected.
Definition at line 226 of file ut_generic_reduce.cpp.
References jb::testing::defaults::size.