JayBeams: jb/itch5/ut_ipo_quoting_period_update_message.cpp File Reference
ut_ipo_quoting_period_update_message.cpp File Reference
#include <jb/itch5/ipo_quoting_period_update_message.hpp>
#include <jb/itch5/testing/data.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (decode_ipo_quoting_period_update_message)
BOOST_AUTO_TEST_CASE (stream_ipo_quoting_period_update_message)
BOOST_AUTO_TEST_CASE (simple_ipo_quotation_release_qualifier)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/3]
BOOST_AUTO_TEST_CASE (decode_ipo_quoting_period_update_message)
Test:
Verify that the jb::itch5::ipo_quoting_period_update_message decoder works as expected.
Definition at line 10 of file ut_ipo_quoting_period_update_message.cpp.
References jb::itch5::testing::expected_ts(), jb::itch5::testing::ipo_quoting_period_update(), jb::itch5::ipo_quoting_period_update_message::message_type, and jb::itch5::decoder< validate, T >::r().
BOOST_AUTO_TEST_CASE() [2/3]
BOOST_AUTO_TEST_CASE (stream_ipo_quoting_period_update_message)
Test:
Verify that jb::itch5::ipo_quoting_period_update_message iostream operator works as expected.
Definition at line 50 of file ut_ipo_quoting_period_update_message.cpp.
References jb::itch5::testing::ipo_quoting_period_update(), and jb::itch5::decoder< validate, T >::r().
BOOST_AUTO_TEST_CASE() [3/3]
BOOST_AUTO_TEST_CASE (simple_ipo_quotation_release_qualifier)
Test:
Verify that ipo_quotation_release_qualifier_t works as expected.
Definition at line 71 of file ut_ipo_quoting_period_update_message.cpp.