JayBeams: jb/itch5/ut_market_participant_position_message.cpp File Reference
ut_market_participant_position_message.cpp File Reference
#include <jb/itch5/market_participant_position_message.hpp>
#include <jb/itch5/testing/data.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (decode_market_participant_position_message)
BOOST_AUTO_TEST_CASE (stream_market_participant_position_message)
BOOST_AUTO_TEST_CASE (simple_primary_market_maker)
BOOST_AUTO_TEST_CASE (simple_market_maker_mode)
BOOST_AUTO_TEST_CASE (simple_market_participant_state)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/5]
BOOST_AUTO_TEST_CASE (decode_market_participant_position_message)
Test:
Verify that the jb::itch5::market_participant_position_message decoder works as expected.
Definition at line 10 of file ut_market_participant_position_message.cpp.
References jb::itch5::testing::expected_ts(), jb::itch5::testing::market_participant_position(), jb::itch5::market_participant_position_message::message_type, and jb::itch5::decoder< validate, T >::r().
BOOST_AUTO_TEST_CASE() [2/5]
BOOST_AUTO_TEST_CASE (stream_market_participant_position_message)
Test:
Verify that jb::itch5::market_participant_position_message iostream operator works as expected.
Definition at line 48 of file ut_market_participant_position_message.cpp.
References jb::itch5::testing::market_participant_position(), and jb::itch5::decoder< validate, T >::r().
BOOST_AUTO_TEST_CASE() [3/5]
BOOST_AUTO_TEST_CASE (simple_primary_market_maker)
Test:
Verify that primary_market_maker_t works as expected.
Definition at line 70 of file ut_market_participant_position_message.cpp.
BOOST_AUTO_TEST_CASE() [4/5]
BOOST_AUTO_TEST_CASE (simple_market_maker_mode)
Test:
Verify that market_maker_mode_t works as expected.
Definition at line 80 of file ut_market_participant_position_message.cpp.
BOOST_AUTO_TEST_CASE() [5/5]
BOOST_AUTO_TEST_CASE (simple_market_participant_state)
Test:
Verify that market_participant_state_t works as expected.
Definition at line 90 of file ut_market_participant_position_message.cpp.