JayBeams: jb/testing/ut_delay_timeseries.cpp File Reference
ut_delay_timeseries.cpp File Reference
#include <jb/testing/delay_timeseries.hpp>
#include <jb/testing/create_triangle_timeseries.hpp>
#include <boost/test/unit_test.hpp>
#include <chrono>
Functions
std::ostream & std::operator<< (std::ostream &os, std::pair< std::ptrdiff_t, float > const &x)
BOOST_AUTO_TEST_CASE (delay_timeseries_periodic_default)
BOOST_AUTO_TEST_CASE (extrapolate_periodic)
BOOST_AUTO_TEST_CASE (delay_timeseries_zeroes_default)
Function Documentation
BOOST_AUTO_TEST_CASE (delay_timeseries_periodic_default)
Test:
Test jb::testing::delay_timeseries_periodic with default types
Usually I do not spend time testing helper functions for tests, but in this case the helper has a lot of template code and we want to validate this before too long.
Definition at line 24 of file ut_delay_timeseries.cpp.
References jb::testing::create_triangle_timeseries(), and jb::testing::delay_timeseries_periodic().
BOOST_AUTO_TEST_CASE (extrapolate_periodic)
Test:
Improve coverage for jb::testing::extrapolate_periodic.
Definition at line 44 of file ut_delay_timeseries.cpp.
BOOST_AUTO_TEST_CASE (delay_timeseries_zeroes_default)
Test:
Test jb::testing::delay_timeseries_zeroes with default types
Usually I do not spend time testing helper functions for tests, but in this case the helper has a lot of template code and we want to validate this before too long.
Definition at line 63 of file ut_delay_timeseries.cpp.
References jb::testing::create_triangle_timeseries(), and jb::testing::delay_timeseries_zeroes().