JayBeams: jb/itch5/ut_array_based_order_book.cpp File Reference
ut_array_based_order_book.cpp File Reference
#include <jb/itch5/array_based_order_book.hpp>
#include <jb/itch5/testing/ut_type_based_order_book.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (array_based_order_book_trivial)
BOOST_AUTO_TEST_CASE (array_based_order_book_test)
BOOST_AUTO_TEST_CASE (array_based_order_book_errors)
BOOST_AUTO_TEST_CASE (array_based_order_book_buy)
BOOST_AUTO_TEST_CASE (array_based_order_book_sell)
BOOST_AUTO_TEST_CASE (array_based_order_book_buy_range)
BOOST_AUTO_TEST_CASE (array_based_order_book_sell_range)
BOOST_AUTO_TEST_CASE (array_based_order_book_buy_small_tick)
BOOST_AUTO_TEST_CASE (array_based_order_book_sell_small_tick)
BOOST_AUTO_TEST_CASE (array_based_order_book_sell_small_tick_bug01)
BOOST_AUTO_TEST_CASE (array_based_order_book_config_simple)
Function Documentation
BOOST_AUTO_TEST_CASE (array_based_order_book_trivial)
Test:
Trivial verification that array_based_order_book works as expected.
Definition at line 9 of file ut_array_based_order_book.cpp.
BOOST_AUTO_TEST_CASE (array_based_order_book_test)
Test:
Verify that array_based_order_book handles add and reduce as expected.
Definition at line 18 of file ut_array_based_order_book.cpp.
BOOST_AUTO_TEST_CASE (array_based_order_book_errors)
Test:
Verify that array_based_order_book handles errors as expected.
Definition at line 26 of file ut_array_based_order_book.cpp.
BOOST_AUTO_TEST_CASE (array_based_order_book_buy)
Test:
Verify that the buy side of array_based_order_book works as expected.
Test inside changes at the top levels, and one price moved from bottom to top to become the new inside.
Definition at line 38 of file ut_array_based_order_book.cpp.
References jb::itch5::array_based_book_side< compare_t >::add_order(), jb::itch5::array_based_book_side< compare_t >::best_quote(), jb::itch5::array_based_book_side< compare_t >::count(), jb::itch5::defaults::max_size, jb::itch5::array_based_book_side< compare_t >::reduce_order(), and jb::itch5::array_based_book_side< compare_t >::worst_quote().
BOOST_AUTO_TEST_CASE (array_based_order_book_sell)
Test:
Verity that the sell side of array_based_order_book works as expected.
Test inside changes at the top levels, and one price moved from bottom to top to become the new inside.
Definition at line 150 of file ut_array_based_order_book.cpp.
References jb::itch5::array_based_book_side< compare_t >::add_order(), jb::itch5::array_based_book_side< compare_t >::best_quote(), jb::itch5::array_based_book_side< compare_t >::count(), jb::itch5::defaults::max_size, jb::itch5::array_based_book_side< compare_t >::reduce_order(), and jb::itch5::array_based_book_side< compare_t >::worst_quote().
BOOST_AUTO_TEST_CASE (array_based_order_book_buy_range)
Test:
Verify that the buy side of array_based_order_book works as expected.
Works adding and removing prices at the limit of top level range to verify move form and to the bottom level work as expected on those border cases.
Definition at line 266 of file ut_array_based_order_book.cpp.
References jb::itch5::array_based_book_side< compare_t >::add_order(), jb::itch5::array_based_book_side< compare_t >::count(), jb::itch5::defaults::max_size, and jb::itch5::array_based_book_side< compare_t >::reduce_order().
BOOST_AUTO_TEST_CASE (array_based_order_book_sell_range)
Test:
Verify that the buy side of array_based_order_book works as expected.
Works adding and removing prices at the limit of top level range to verify move form and to the bottom level work as expected on those border cases.
Definition at line 360 of file ut_array_based_order_book.cpp.
References jb::itch5::array_based_book_side< compare_t >::add_order(), jb::itch5::array_based_book_side< compare_t >::count(), jb::itch5::defaults::max_size, and jb::itch5::array_based_book_side< compare_t >::reduce_order().
BOOST_AUTO_TEST_CASE (array_based_order_book_buy_small_tick)
Test:
Verify that the buy side of array_based_order_book works as expected.
Test suite for prices below $1.00. A smaller tick offset is used to facilitate the tests Works adding and removing prices at the limit of top level range to verify move form and to the bottom level work as expected on those border cases.
Definition at line 460 of file ut_array_based_order_book.cpp.
References jb::itch5::array_based_book_side< compare_t >::add_order(), jb::itch5::array_based_book_side< compare_t >::count(), jb::itch5::defaults::max_size, and jb::itch5::array_based_book_side< compare_t >::reduce_order().
BOOST_AUTO_TEST_CASE (array_based_order_book_sell_small_tick)
Test:
Verify that the buy side of array_based_order_book works as expected.
Test suite for prices below $1.00. A smaller tick offset is used to facilitate the tests Works adding and removing prices at the limit of top level range to verify move form and to the bottom level work as expected on those border cases.
Definition at line 547 of file ut_array_based_order_book.cpp.
References jb::itch5::array_based_book_side< compare_t >::add_order(), jb::itch5::array_based_book_side< compare_t >::count(), jb::itch5::defaults::max_size, and jb::itch5::array_based_book_side< compare_t >::reduce_order().
BOOST_AUTO_TEST_CASE (array_based_order_book_sell_small_tick_bug01)
Test:
itch5arrayinside exception generated.
Adding test case to fix the problem.
Definition at line 619 of file ut_array_based_order_book.cpp.
References jb::itch5::array_based_book_side< compare_t >::add_order(), jb::itch5::defaults::max_size, and jb::itch5::array_based_book_side< compare_t >::reduce_order().
BOOST_AUTO_TEST_CASE (array_based_order_book_config_simple)
Test:
Verify that array_based_order_book::config works as expected.
Definition at line 659 of file ut_array_based_order_book.cpp.
References jb::itch5::defaults::max_size.