JayBeams: jb/itch5/ut_broken_trade_message.cpp File Reference
ut_broken_trade_message.cpp File Reference
#include <jb/itch5/broken_trade_message.hpp>
#include <jb/itch5/testing_data.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (decode_broken_trade_message)
BOOST_AUTO_TEST_CASE (stream_broken_trade_message)
Function Documentation
BOOST_AUTO_TEST_CASE (decode_broken_trade_message)
Test:
Verify that the jb::itch5::broken_trade_message decoder works as expected.
Definition at line 10 of file ut_broken_trade_message.cpp.
References jb::itch5::testing::broken_trade(), jb::itch5::testing::expected_ts(), jb::itch5::broken_trade_message::message_type, and jb::itch5::decoder< validate, T >::r().
BOOST_AUTO_TEST_CASE (stream_broken_trade_message)
Test:
Verify that jb::itch5::broken_trade_message iostream operator works as expected.
Definition at line 38 of file ut_broken_trade_message.cpp.
References jb::itch5::testing::broken_trade(), and jb::itch5::decoder< validate, T >::r().