JayBeams: jb/ut_fileio.cpp File Reference
ut_fileio.cpp File Reference
#include <jb/fileio.hpp>
#include <boost/filesystem.hpp>
#include <boost/test/unit_test.hpp>
Functions
void check_read_write (boost::filesystem::path const &path)
Implement the common part of the tests.
BOOST_AUTO_TEST_CASE (fileio_basic)
BOOST_AUTO_TEST_CASE (fileio_gz)
BOOST_AUTO_TEST_CASE (fileio_stdout)
Function Documentation
BOOST_AUTO_TEST_CASE (fileio_basic)
Test:
Verify we can read and write regular files...
Definition at line 42 of file ut_fileio.cpp.
References check_read_write().
BOOST_AUTO_TEST_CASE (fileio_gz)
Test:
Verify we can read and write regular files...
Definition at line 53 of file ut_fileio.cpp.
References check_read_write().
BOOST_AUTO_TEST_CASE (fileio_stdout)
Test:
Verify we can write to stdout.
Definition at line 64 of file ut_fileio.cpp.
References jb::open_output_file().
void check_read_write (boost::filesystem::path const & path)
Implement the common part of the tests.
Definition at line 9 of file ut_fileio.cpp.
References jb::open_input_file(), and jb::open_output_file().
Referenced by BOOST_AUTO_TEST_CASE().