JayBeams: jb/itch5/ut_make_socket_udp_recv.cpp File Reference
ut_make_socket_udp_recv.cpp File Reference
#include <jb/itch5/make_socket_udp_recv.hpp>
#include <jb/itch5/testing/mock_udp_socket.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_recv_compile)
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_recv_basic)
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_recv_multicast_ipv4)
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_recv_multicast_ipv6)
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_recv_listen_address)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/5]
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_recv_compile)
Test:
Verify that jb::itch5::make_socket_udp_recv compiles.
Definition at line 9 of file ut_make_socket_udp_recv.cpp.
References jb::itch5::udp_receiver_config::address, and jb::itch5::make_socket_udp_recv().
BOOST_AUTO_TEST_CASE() [2/5]
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_recv_basic)
Definition at line 23 of file ut_make_socket_udp_recv.cpp.
References jb::itch5::detail::setup_socket_udp_recv().
BOOST_AUTO_TEST_CASE() [3/5]
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_recv_multicast_ipv4)
Definition at line 41 of file ut_make_socket_udp_recv.cpp.
References jb::itch5::detail::setup_socket_udp_recv().
BOOST_AUTO_TEST_CASE() [4/5]
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_recv_multicast_ipv6)
Definition at line 63 of file ut_make_socket_udp_recv.cpp.
References jb::itch5::detail::setup_socket_udp_recv().
BOOST_AUTO_TEST_CASE() [5/5]
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_recv_listen_address)
Definition at line 84 of file ut_make_socket_udp_recv.cpp.
References jb::itch5::detail::setup_socket_udp_recv().