JayBeams: jb/ehs/ut_acceptor.cpp File Reference
ut_acceptor.cpp File Reference
#include <jb/ehs/acceptor.hpp>
#include <thread>
#include <boost/asio/io_service.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (acceptor_base)
BOOST_AUTO_TEST_CASE (connection_read_error)
BOOST_AUTO_TEST_CASE (acceptor_multiple_connections)
BOOST_AUTO_TEST_CASE (connection_multiple_requests)
BOOST_AUTO_TEST_CASE (acceptor_double_shutdown)
BOOST_AUTO_TEST_CASE (acceptor_on_accept_closed)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/6]
BOOST_AUTO_TEST_CASE (acceptor_base)
Test:
Verify that jb::ehs::connection + jb::ehs::acceptor work as expected.
Definition at line 24 of file ut_acceptor.cpp.
References jb::ehs::acceptor::local_endpoint(), and jb::ehs::acceptor::shutdown().
BOOST_AUTO_TEST_CASE() [2/6]
BOOST_AUTO_TEST_CASE (connection_read_error)
Test:
Verify that jb::ehs::connection handles read errors.
Definition at line 91 of file ut_acceptor.cpp.
References jb::ehs::acceptor::local_endpoint(), and jb::ehs::acceptor::shutdown().
BOOST_AUTO_TEST_CASE() [3/6]
BOOST_AUTO_TEST_CASE (acceptor_multiple_connections)
Test:
Verify that jb::ehs::acceptor accepts multiple connections.
Definition at line 193 of file ut_acceptor.cpp.
References jb::ehs::acceptor::local_endpoint(), and jb::ehs::acceptor::shutdown().
BOOST_AUTO_TEST_CASE() [4/6]
BOOST_AUTO_TEST_CASE (connection_multiple_requests)
Test:
Verify that jb::ehs::connection can handle multiple requests.
Definition at line 226 of file ut_acceptor.cpp.
References jb::ehs::acceptor::local_endpoint(), and jb::ehs::acceptor::shutdown().
BOOST_AUTO_TEST_CASE() [5/6]
BOOST_AUTO_TEST_CASE (acceptor_double_shutdown)
Test:
Verify that jb::ehs::acceptor shutdown is safe to call twice.
Definition at line 291 of file ut_acceptor.cpp.
References jb::ehs::acceptor::shutdown().
BOOST_AUTO_TEST_CASE() [6/6]
BOOST_AUTO_TEST_CASE (acceptor_on_accept_closed)
Test:
Improve coverage forjb::ehs::acceptor.
Definition at line 310 of file ut_acceptor.cpp.
References jb::ehs::acceptor::shutdown().