JayBeams: jb/itch5/ut_make_socket_udp_common.cpp File Reference
ut_make_socket_udp_common.cpp File Reference
#include <jb/itch5/make_socket_udp_common.hpp>
#include <jb/itch5/testing/mock_udp_socket.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_common_basic)
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_common_debug)
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_common_linger)
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_common_rcvbuf)
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_common_sndbuf)
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_common_rcvlow)
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_common_sndlow)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/7]
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_common_basic)
Definition at line 9 of file ut_make_socket_udp_common.cpp.
References jb::itch5::make_socket_udp_common().
BOOST_AUTO_TEST_CASE() [2/7]
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_common_debug)
Definition at line 17 of file ut_make_socket_udp_common.cpp.
References jb::itch5::make_socket_udp_common().
BOOST_AUTO_TEST_CASE() [3/7]
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_common_linger)
Definition at line 27 of file ut_make_socket_udp_common.cpp.
References jb::itch5::make_socket_udp_common().
BOOST_AUTO_TEST_CASE() [4/7]
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_common_rcvbuf)
Definition at line 38 of file ut_make_socket_udp_common.cpp.
References jb::itch5::make_socket_udp_common().
BOOST_AUTO_TEST_CASE() [5/7]
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_common_sndbuf)
Definition at line 50 of file ut_make_socket_udp_common.cpp.
References jb::itch5::make_socket_udp_common().
BOOST_AUTO_TEST_CASE() [6/7]
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_common_rcvlow)
Definition at line 62 of file ut_make_socket_udp_common.cpp.
References jb::itch5::make_socket_udp_common().
BOOST_AUTO_TEST_CASE() [7/7]
BOOST_AUTO_TEST_CASE (itch5_make_socket_udp_common_sndlow)
Definition at line 74 of file ut_make_socket_udp_common.cpp.
References jb::itch5::make_socket_udp_common().