JayBeams: jb/ut_event_rate_estimator.cpp File Reference
ut_event_rate_estimator.cpp File Reference
#include <jb/event_rate_estimator.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (event_rate_estimator_base)
BOOST_AUTO_TEST_CASE (event_rate_estimator_jump)
BOOST_AUTO_TEST_CASE (event_rate_estimator_milliseconds)
BOOST_AUTO_TEST_CASE (event_rate_estimator_errors)
Function Documentation
BOOST_AUTO_TEST_CASE (event_rate_estimator_base)
Test:
Test default construction and basic operations.
Definition at line 8 of file ut_event_rate_estimator.cpp.
References jb::fftw::detail::nsamples(), and jb::event_rate_estimator< duration_t, counter_t >::sample().
BOOST_AUTO_TEST_CASE (event_rate_estimator_jump)
Test:
Verify that event_rate_estimator optimizes big jumps in time.
Definition at line 52 of file ut_event_rate_estimator.cpp.
References jb::fftw::detail::nsamples(), and jb::event_rate_estimator< duration_t, counter_t >::sample().
BOOST_AUTO_TEST_CASE (event_rate_estimator_milliseconds)
Test:
Verify that estimators can use a different bucket size.
Definition at line 116 of file ut_event_rate_estimator.cpp.
References jb::fftw::detail::nsamples(), and jb::event_rate_estimator< duration_t, counter_t >::sample().
BOOST_AUTO_TEST_CASE (event_rate_estimator_errors)
Test:
Test error cases
Definition at line 161 of file ut_event_rate_estimator.cpp.