JayBeams: jb/ut_book_depth_statistics.cpp File Reference
ut_book_depth_statistics.cpp File Reference
#include <jb/book_depth_statistics.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (book_depth_statistics_simple)
BOOST_AUTO_TEST_CASE (book_depth_statistics_print_csv)
BOOST_AUTO_TEST_CASE (book_depth_statististics_config_simple)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/3]
BOOST_AUTO_TEST_CASE (book_depth_statistics_simple)
Test:
Verify that jb::book_depth_statistics works as expected.
Definition at line 8 of file ut_book_depth_statistics.cpp.
References jb::book_depth_statistics::sample().
BOOST_AUTO_TEST_CASE() [2/3]
BOOST_AUTO_TEST_CASE (book_depth_statistics_print_csv)
Test:
Test jb::book_depth_statistics csv output.
Definition at line 22 of file ut_book_depth_statistics.cpp.
References jb::book_depth_statistics::print_csv(), jb::book_depth_statistics::print_csv_header(), and jb::book_depth_statistics::sample().
BOOST_AUTO_TEST_CASE() [3/3]
BOOST_AUTO_TEST_CASE (book_depth_statististics_config_simple)
Test:
Verify that jb::book_depth_statistics::config works as expected.
Definition at line 72 of file ut_book_depth_statistics.cpp.
References jb::defaults::max_book_depth.