JayBeams: jb/ut_cpu_set.cpp File Reference
ut_cpu_set.cpp File Reference
#include <jb/convert_cpu_set.hpp>
#include <jb/cpu_set.hpp>
#include <boost/test/unit_test.hpp>
#include <sstream>
Functions
BOOST_AUTO_TEST_CASE (cpu_set_basic)
BOOST_AUTO_TEST_CASE (cpu_set_ostream)
BOOST_AUTO_TEST_CASE (cpu_set_istream)
BOOST_AUTO_TEST_CASE (cpu_set_clear)
BOOST_AUTO_TEST_CASE (cpu_set_parse_invalid)
BOOST_AUTO_TEST_CASE (cpu_set_yaml_convert)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/6]
BOOST_AUTO_TEST_CASE (cpu_set_basic)
Test:
Verify that basic operations on jb::cpu_set work as expected.
Definition at line 11 of file ut_cpu_set.cpp.
References jb::cpu_set::capacity(), jb::cpu_set::count(), jb::cpu_set::set(), and jb::cpu_set::status().
BOOST_AUTO_TEST_CASE() [2/6]
BOOST_AUTO_TEST_CASE (cpu_set_ostream)
Test:
Verify that jb::cpu_set output streaming works as expected.
Definition at line 99 of file ut_cpu_set.cpp.
References jb::cpu_set::set().
BOOST_AUTO_TEST_CASE() [3/6]
BOOST_AUTO_TEST_CASE (cpu_set_istream)
Test:
Verify that jb::cpu_set input streaming works as expected.
Definition at line 149 of file ut_cpu_set.cpp.
BOOST_AUTO_TEST_CASE() [4/6]
BOOST_AUTO_TEST_CASE (cpu_set_clear)
Test:
Verify that the clear() operation works as expected for a range.
Definition at line 206 of file ut_cpu_set.cpp.
References jb::cpu_set::clear(), jb::cpu_set::count(), jb::cpu_set::set(), and jb::cpu_set::status().
BOOST_AUTO_TEST_CASE() [5/6]
BOOST_AUTO_TEST_CASE (cpu_set_parse_invalid)
Test:
Verify that the parse() function works as expected for invalid inputs.
Definition at line 222 of file ut_cpu_set.cpp.
References jb::cpu_set::parse().
BOOST_AUTO_TEST_CASE() [6/6]
BOOST_AUTO_TEST_CASE (cpu_set_yaml_convert)
Test:
Verify that the YAML conversion functions work as expected.
Definition at line 236 of file ut_cpu_set.cpp.
References YAML::convert< jb::cpu_set >::decode(), YAML::convert< jb::cpu_set >::encode(), and jb::cpu_set::parse().