JayBeams: jb/opencl/ut_device_selector.cpp File Reference
ut_device_selector.cpp File Reference
#include <jb/opencl/config.hpp>
#include <jb/opencl/device_selector.hpp>
#include <boost/compute/system.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (opencl_device_selector_by_name)
BOOST_AUTO_TEST_CASE (opencl_device_selector_empty)
BOOST_AUTO_TEST_CASE (opencl_device_selector_bestcpu)
BOOST_AUTO_TEST_CASE (opencl_device_selector_bestgpu)
BOOST_AUTO_TEST_CASE (opencl_device_selector_no_config)
BOOST_AUTO_TEST_CASE (opencl_device_selector_system_default)
BOOST_AUTO_TEST_CASE (opencl_device_selector_filter_failure)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/7]
BOOST_AUTO_TEST_CASE (opencl_device_selector_by_name)
Test:
Verify that we can select devices by name.
Definition at line 10 of file ut_device_selector.cpp.
References jb::opencl::defaults::device_name(), and jb::opencl::device_selector().
BOOST_AUTO_TEST_CASE() [2/7]
BOOST_AUTO_TEST_CASE (opencl_device_selector_empty)
Test:
Verify that the selection with an empty name works as expected.
Definition at line 25 of file ut_device_selector.cpp.
References jb::opencl::device_selector().
BOOST_AUTO_TEST_CASE() [3/7]
BOOST_AUTO_TEST_CASE (opencl_device_selector_bestcpu)
Test:
Verify that the default selection works as expected.
Definition at line 38 of file ut_device_selector.cpp.
References jb::opencl::defaults::device_name(), and jb::opencl::device_selector().
BOOST_AUTO_TEST_CASE() [4/7]
BOOST_AUTO_TEST_CASE (opencl_device_selector_bestgpu)
Test:
Verify that the default selection works as expected.
Definition at line 61 of file ut_device_selector.cpp.
References jb::opencl::defaults::device_name(), and jb::opencl::device_selector().
BOOST_AUTO_TEST_CASE() [5/7]
BOOST_AUTO_TEST_CASE (opencl_device_selector_no_config)
Test:
Verify that the device selector without config works as expected.
Definition at line 85 of file ut_device_selector.cpp.
References jb::opencl::device_selector().
BOOST_AUTO_TEST_CASE() [6/7]
BOOST_AUTO_TEST_CASE (opencl_device_selector_system_default)
Test:
Verify that the device selector for "SYSTEM:DEFAULT" works as expected.
Definition at line 99 of file ut_device_selector.cpp.
References jb::opencl::defaults::device_name(), and jb::opencl::device_selector().
BOOST_AUTO_TEST_CASE() [7/7]
BOOST_AUTO_TEST_CASE (opencl_device_selector_filter_failure)
Test:
Verify that detail::best_device() helper fails as expected.
Definition at line 111 of file ut_device_selector.cpp.
References jb::opencl::detail::best_device().