JayBeams: jb/itch5/ut_process_iostream_mlist.cpp File Reference
jb/itch5/ut_process_iostream_mlist.cpp File Reference
#include <jb/itch5/process_iostream_mlist.hpp>
#include <jb/itch5/system_event_message.hpp>
#include <jb/itch5/stock_directory_message.hpp>
#include <jb/itch5/add_order_message.hpp>
#include <jb/itch5/testing_data.hpp>
#include <skye/mock_function.hpp>
#include <skye/mock_template_function.hpp>
#include <initializer_list>
Functions
BOOST_AUTO_TEST_CASE (process_iostream_mlist_simple)
BOOST_AUTO_TEST_CASE (process_iostream_mlist_errors)
Function Documentation
BOOST_AUTO_TEST_CASE (process_iostream_mlist_simple)
Test:
Verify that jb::itch5::process_iostream_mlist<> works as expected.
Definition at line 36 of file ut_process_iostream_mlist.cpp.
References jb::itch5::testing::add_order(), is, jb::itch5::process_iostream_mlist(), jb::itch5::testing::stock_directory(), jb::itch5::testing::system_event(), and jb::itch5::testing::trade().
BOOST_AUTO_TEST_CASE (process_iostream_mlist_errors)
Test:
Verify that jb::itch5::process_iostream_mlist<> exits gracefully on I/O errors.
Definition at line 71 of file ut_process_iostream_mlist.cpp.
References is, jb::itch5::process_iostream_mlist(), jb::itch5::testing::stock_directory(), and jb::itch5::testing::system_event().