JayBeams: jb/ut_merge_yaml.cpp File Reference
ut_merge_yaml.cpp File Reference
#include <jb/merge_yaml.hpp>
#include <boost/test/unit_test.hpp>
#include <string>
Functions
BOOST_AUTO_TEST_CASE (merge_yaml_map)
BOOST_AUTO_TEST_CASE (merge_yaml_sequences)
BOOST_AUTO_TEST_CASE (merge_yaml_sequences_of_maps)
BOOST_AUTO_TEST_CASE (merge_yaml_nested)
BOOST_AUTO_TEST_CASE (merge_yaml_invalid_source)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/5]
BOOST_AUTO_TEST_CASE (merge_yaml_map)
Test:
Verify merging of two maps.
Definition at line 9 of file ut_merge_yaml.cpp.
References jb::yaml::merge_node().
BOOST_AUTO_TEST_CASE() [2/5]
BOOST_AUTO_TEST_CASE (merge_yaml_sequences)
Test:
Verify merging of two sequences.
Definition at line 22 of file ut_merge_yaml.cpp.
References jb::yaml::merge_node().
BOOST_AUTO_TEST_CASE() [3/5]
BOOST_AUTO_TEST_CASE (merge_yaml_sequences_of_maps)
Test:
Verify merging of sequences of maps
Definition at line 44 of file ut_merge_yaml.cpp.
References jb::yaml::merge_node().
BOOST_AUTO_TEST_CASE() [4/5]
BOOST_AUTO_TEST_CASE (merge_yaml_nested)
Test:
Verify merging of two nested maps.
Definition at line 67 of file ut_merge_yaml.cpp.
References jb::yaml::merge_node().
BOOST_AUTO_TEST_CASE() [5/5]
BOOST_AUTO_TEST_CASE (merge_yaml_invalid_source)
Test:
Verify merging of invalid nodes throws the right thing.
Definition at line 83 of file ut_merge_yaml.cpp.
References jb::yaml::merge_node().